// apps/web/app/dashboard/page.tsx
/**
 * /dashboard — maker home.
 *
 * Lists quick actions (Ship new app, View your apps) and links to the
 * real feature surfaces. Week 4+ fills this out with feedback inbox,
 * deploys log, analytics tiles.
 */
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { auth, signOut } from '@/lib/auth';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export default async function DashboardPage() {
  const session = await auth();
  if (!session?.user) {
    redirect('/auth/signin');
  }

  async function handleSignOut() {
    'use server';
    await signOut({ redirectTo: '/' });
  }

  return (
    <main className="min-h-screen px-6 py-16">
      <div className="max-w-4xl mx-auto space-y-10">
        <header className="space-y-2">
          <p className="text-xs uppercase tracking-widest text-brand-500 font-mono">
            Dashboard
          </p>
          <h1 className="text-4xl font-bold">
            Welcome{session.user.name ? `, ${session.user.name}` : ''}.
          </h1>
          <p className="text-neutral-600 dark:text-neutral-400">
            Signed in as <strong>{session.user.email}</strong>
          </p>
        </header>

        <section className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Link
            href="/new"
            className="rounded-xl border border-brand-500/40 bg-brand-50/40 dark:bg-brand-900/10 p-6 hover:border-brand-500 transition-colors"
          >
            <p className="text-xs uppercase tracking-widest text-brand-500 font-mono">
              Action
            </p>
            <h2 className="text-xl font-semibold mt-1">Ship a new app</h2>
            <p className="text-sm text-neutral-600 dark:text-neutral-400 mt-2">
              Upload a zip or connect a GitHub repo. Live in under a minute.
            </p>
          </Link>

          <Link
            href="/dashboard/apps"
            className="rounded-xl border border-neutral-300 dark:border-neutral-700 p-6 hover:border-neutral-400 transition-colors"
          >
            <p className="text-xs uppercase tracking-widest text-neutral-500 font-mono">
              Your stuff
            </p>
            <h2 className="text-xl font-semibold mt-1">Your apps</h2>
            <p className="text-sm text-neutral-600 dark:text-neutral-400 mt-2">
              All apps you've shipped, with status, versions, and live URLs.
            </p>
          </Link>
        </section>

        <form action={handleSignOut}>
          <button
            type="submit"
            className="inline-flex h-10 items-center rounded-full border border-neutral-300 dark:border-neutral-700 px-5 text-sm font-medium hover:border-neutral-400 transition-colors"
          >
            Sign out
          </button>
        </form>
      </div>
    </main>
  );
}

// apps/platform/src/routes/dashboard/+page.svelte
<script lang="ts">
  import type { LayoutData } from './$types';

  let { data }: { data: LayoutData } = $props();
  const apps = data.myApps;
</script>

<svelte:head>
  <title>Dashboard · Shippie</title>
</svelte:head>

<header class="header">
  <p class="eyebrow">Dashboard</p>
  <h1>Welcome{data.user.displayName ? `, ${data.user.displayName}` : ''}.</h1>
  <p class="lede">Signed in as <strong>{data.user.email}</strong></p>
</header>

<section class="quick">
  <a class="card primary" href="/new">
    <p class="card-eyebrow">Action</p>
    <h2>Ship a new app</h2>
    <p>Upload a zip, wrap a hosted URL, or connect a GitHub repo. Live in under a minute.</p>
  </a>

  <a class="card" href="/dashboard/apps">
    <p class="card-eyebrow">Your stuff</p>
    <h2>Your apps ({apps.length})</h2>
    <p>Versions, status, deploys, visibility.</p>
  </a>
</section>

{#if apps.length > 0}
  <section class="recent">
    <h2 class="section-title">Recent</h2>
    <ul>
      {#each apps.slice(0, 5) as app (app.id)}
        <li>
          <span class="swatch" style:background={app.themeColor}></span>
          <a href={`/dashboard/apps/${app.slug}`}><strong>{app.name}</strong></a>
          <span class="status status-{app.latestDeployStatus ?? 'draft'}">{app.latestDeployStatus ?? 'draft'}</span>
          <span class="vis">{app.visibilityScope}</span>
        </li>
      {/each}
    </ul>
  </section>
{/if}

<form method="POST" action="/auth/logout" class="logout">
  <button type="submit">Sign out</button>
</form>

<style>
  .header { margin-bottom: 2rem; }
  .eyebrow {
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    font-size: 11px;
    letter-spacing: 0.16em;
    text-transform: uppercase;
    color: #E8603C;
    margin: 0 0 0.25rem 0;
  }
  h1 { font-family: 'Fraunces', Georgia, serif; font-size: 2.5rem; margin: 0; letter-spacing: -0.02em; }
  .lede { color: #8B847A; }
  .quick { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
  .card {
    display: block;
    padding: 1.5rem;
    border: 1px solid #E5DDC8;
    text-decoration: none;
    color: inherit;
    border-radius: 12px;
    transition: border-color 0.12s;
  }
  .card:hover { border-color: #E8603C; }
  .card.primary { border-color: rgba(232,96,60,0.3); background: rgba(232,96,60,0.04); }
  .card h2 { margin: 0.25rem 0; font-size: 1.25rem; }
  .card p { color: #8B847A; margin: 0; font-size: 14px; }
  .card-eyebrow {
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    font-size: 11px;
    letter-spacing: 0.16em;
    text-transform: uppercase;
    color: #E8603C;
    margin: 0;
  }
  .recent ul { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 0.25rem; }
  .recent li {
    display: grid;
    grid-template-columns: auto 1fr auto auto;
    gap: 0.75rem;
    align-items: center;
    padding: 0.5rem 0.75rem;
    border-bottom: 1px solid rgba(0,0,0,0.06);
  }
  .swatch { width: 12px; height: 12px; border-radius: 3px; }
  .status { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 11px; padding: 2px 8px; border-radius: 999px; background: rgba(0,0,0,0.05); }
  .status-success { background: rgba(46,125,91,0.15); color: #2E7D5B; }
  .status-failed { background: rgba(180,63,42,0.15); color: #B43F2A; }
  .vis { font-size: 12px; color: #8B847A; }
  .section-title { font-family: 'Fraunces', Georgia, serif; font-size: 1.25rem; margin: 1rem 0 0.5rem 0; }
  .logout { margin-top: 2rem; }
  .logout button {
    background: transparent; border: 1px solid #E5DDC8; padding: 0.5rem 1.5rem;
    border-radius: 999px; font-size: 13px; cursor: pointer; color: inherit;
  }
  @media (prefers-color-scheme: dark) {
    .card { border-color: #2A251E; }
    .card.primary { background: rgba(232,96,60,0.08); }
    .recent li { border-color: rgba(255,255,255,0.05); }
    .status { background: rgba(255,255,255,0.05); }
    .logout button { border-color: #2A251E; }
  }
</style>
