// apps/web/app/dashboard/[appSlug]/enhancements/page.tsx
import type { Metadata } from 'next';
import { loadAppProfileForOwner } from '@/lib/dashboard/profile-loader';
import { readShippieJson } from '@/lib/dashboard/shippie-json';
import { CAPABILITY_CATALOG, extractEnabledCapabilityIds } from './catalog';
import { EnhancementsClient } from './EnhancementsClient';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'Enhancements — Shippie',
};

const RULE_LABEL: Record<string, string> = {
  textures: 'Sensory textures (haptic + sound + visual)',
  wakelock: 'Keep screen awake during use',
  'share-target': 'Receive shared content from other apps',
};

interface PageProps {
  params: Promise<{ appSlug: string }>;
}

export default async function Page({ params }: PageProps) {
  const { appSlug } = await params;
  const [{ profile }, shippieJson] = await Promise.all([
    loadAppProfileForOwner(appSlug),
    readShippieJson(appSlug),
  ]);

  if (!profile) {
    return (
      <main style={{ maxWidth: 720, margin: '0 auto', padding: '40px 24px' }}>
        <h1 style={{ margin: 0, fontSize: 28, fontWeight: 700 }}>Enhancements</h1>
        <p style={{ marginTop: 12, color: '#5C5751' }}>
          This app hasn&rsquo;t been analysed yet. The next deploy will populate this view.
        </p>
        <EnhancementsClient slug={appSlug} initialJson={shippieJson} />
      </main>
    );
  }

  const detected: Array<{ selector: string; rule: string }> = [];
  for (const [selector, rules] of Object.entries(profile.recommended.enhance)) {
    for (const rule of rules) detected.push({ selector, rule });
  }

  const enabled = new Set(extractEnabledCapabilityIds(shippieJson));
  const available = CAPABILITY_CATALOG.filter((c) => !enabled.has(c.id));

  return (
    <main style={{ maxWidth: 720, margin: '0 auto', padding: '40px 24px 80px' }}>
      <header style={{ marginBottom: 28 }}>
        <h1 style={{ margin: 0, fontSize: 30, fontWeight: 700 }}>Enhancements</h1>
        <p style={{ marginTop: 8, color: '#5C5751', fontSize: 15 }}>
          Shippie auto-detected the following capabilities for{' '}
          <strong>{profile.inferredName}</strong>. Override anything in{' '}
          <code>shippie.json</code> below.
        </p>
        <p style={{ marginTop: 4, color: '#8E8A86', fontSize: 13 }}>
          Inferred category:{' '}
          <strong>{profile.category.primary}</strong>
          {profile.category.confidence > 0
            ? ` (${Math.round(profile.category.confidence * 100)}% confidence)`
            : ''}
        </p>
      </header>

      <section>
        <h2 style={{ margin: '0 0 12px', fontSize: 20, fontWeight: 600 }}>
          Active (auto-detected)
        </h2>
        {detected.length === 0 ? (
          <p style={{ color: '#5C5751' }}>No enhancements active.</p>
        ) : (
          <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 6 }}>
            {detected.map(({ selector, rule }) => (
              <li
                key={`${selector}::${rule}`}
                style={{
                  padding: '10px 14px',
                  borderRadius: 10,
                  background: '#F7F4ED',
                  fontSize: 14,
                  display: 'grid',
                  gridTemplateColumns: '1fr auto',
                  gap: 12,
                  alignItems: 'center',
                }}
              >
                <span>{RULE_LABEL[rule] ?? rule}</span>
                <code style={{ fontSize: 12, color: '#5C5751' }}>{selector}</code>
              </li>
            ))}
          </ul>
        )}
      </section>

      <section style={{ marginTop: 32 }}>
        <h2 style={{ margin: '0 0 12px', fontSize: 20, fontWeight: 600 }}>Available (opt-in)</h2>
        {available.length === 0 ? (
          <p style={{ color: '#5C5751' }}>You&rsquo;ve enabled every available capability.</p>
        ) : (
          <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 12 }}>
            {available.map((c) => (
              <li
                key={c.id}
                style={{
                  padding: '14px 16px',
                  borderRadius: 12,
                  border: '1px solid rgba(0,0,0,0.08)',
                  background: 'white',
                }}
              >
                <h3 style={{ margin: 0, fontSize: 16, fontWeight: 600 }}>{c.label}</h3>
                <p style={{ margin: '6px 0 8px', color: '#5C5751', fontSize: 14 }}>{c.blurb}</p>
                <a href={c.docsHref} style={{ color: '#E8603C', fontSize: 14 }}>
                  Docs →
                </a>
              </li>
            ))}
          </ul>
        )}
      </section>

      <EnhancementsClient slug={appSlug} initialJson={shippieJson} />
    </main>
  );
}

// apps/platform/src/routes/maker/apps/[slug]/enhancements/+page.svelte
<script lang="ts">
  import type { PageProps } from './$types';
  import { enhance } from '$app/forms';

  let { data, form }: PageProps = $props();

  // Local editor state, seeded from the loader's serialized JSON.
  let text = $state('');
  let saving = $state(false);
  let resetting = $state(false);
  let resetArmed = $state(false);
  let resetTimer: number | undefined;

  $effect(() => {
    text = data.initialJsonText;
  });

  // Friendly labels for the auto-detected enhance rules.
  const RULE_LABEL: Record<string, string> = {
    textures: 'Sensory textures (haptic + sound + visual)',
    wakelock: 'Keep screen awake during use',
    'share-target': 'Receive shared content from other apps'
  };

  function clearResetIntent() {
    resetArmed = false;
    if (resetTimer) {
      window.clearTimeout(resetTimer);
      resetTimer = undefined;
    }
  }

  function handleResetClick(e: MouseEvent) {
    if (!resetArmed) {
      e.preventDefault();
      resetArmed = true;
      if (resetTimer) window.clearTimeout(resetTimer);
      resetTimer = window.setTimeout(() => {
        resetArmed = false;
        resetTimer = undefined;
      }, 8000);
      return;
    }

    clearResetIntent();
    resetting = true;
    // After the form submit, reset the local state so the textarea
    // clears too; SvelteKit re-runs the loader so data.initialJsonText
    // updates on the next render.
    text = '{}';
  }
</script>

<svelte:head>
  <title>Enhancements · {data.app.name}</title>
</svelte:head>

<a class="back-link" href={`/maker/apps/${data.app.slug}/settings`}>Back to Settings</a>

<header class="head">
  <h1>Enhancements</h1>
  {#if data.profile}
    <p class="lede">
      Shippie auto-detected the following capabilities for
      <strong>{data.profile.inferredName}</strong>. Override anything in
      <code>shippie.json</code> below.
    </p>
    <p class="meta">
      Inferred category: <strong>{data.profile.category.primary}</strong>
      {#if data.profile.category.confidence > 0}
        · {Math.round(data.profile.category.confidence * 100)}% confidence
      {/if}
    </p>
  {:else}
    <p class="lede">
      This app hasn't been analysed yet. The next deploy will populate this view.
    </p>
  {/if}
</header>

{#if data.profile}
  <section class="section">
    <h2>Active (auto-detected)</h2>
    {#if data.detected.length === 0}
      <p class="muted">No enhancements active.</p>
    {:else}
      <ul class="detected">
        {#each data.detected as { selector, rule } (`${selector}::${rule}`)}
          <li>
            <span class="rule">{RULE_LABEL[rule] ?? rule}</span>
            <code class="selector">{selector}</code>
          </li>
        {/each}
      </ul>
    {/if}
  </section>

  <section class="section">
    <h2>Available (opt-in)</h2>
    {#if data.available.length === 0}
      <p class="muted">You've enabled every available capability.</p>
    {:else}
      <ul class="available">
        {#each data.available as cap (cap.id)}
          <li class="cap-card">
            <h3>{cap.label}</h3>
            <p>{cap.blurb}</p>
            <a href={cap.docsHref}>Docs →</a>
          </li>
        {/each}
      </ul>
    {/if}
  </section>
{/if}

<section class="section">
  <h2>shippie.json</h2>
  <p class="muted">Override anything Shippie auto-detected. Saves apply on the next deploy.</p>

  <form
    method="POST"
    action="?/save"
    use:enhance={() => {
      saving = true;
      if (resetArmed) clearResetIntent();
      return async ({ update }) => {
        await update({ reset: false });
        saving = false;
        resetting = false;
      };
    }}
  >
    <textarea
      name="shippieJson"
      bind:value={text}
      rows="14"
      spellcheck="false"
      autocomplete="off"
    ></textarea>

    {#if form?.error}
      <p class="error">{form.error}</p>
    {:else if form?.saved}
      <p class="ok">
        {form.reset ? 'Reset. Next deploy uses auto-detected defaults.' : 'Saved. Next deploy uses the new config.'}
      </p>
    {/if}

    <div class="actions">
      <button type="submit" class="btn primary" disabled={saving || resetting}>
        {saving ? 'Saving…' : 'Save'}
      </button>
      <button
        type="submit"
        formaction="?/reset"
        class="btn secondary"
        disabled={saving || resetting}
        aria-pressed={resetArmed}
        onclick={handleResetClick}
      >
        {resetting ? 'Resetting…' : resetArmed ? 'Tap again to reset' : 'Reset to auto'}
      </button>
    </div>
    {#if resetArmed}
      <p class="warn" role="status">This clears your shippie.json overrides and returns to auto-detected enhancements.</p>
    {/if}
  </form>
</section>

<style>
  .back-link {
    display: inline-block;
    margin-bottom: 1rem;
    color: var(--text-secondary);
    font-size: var(--small-size, 0.9rem);
    text-decoration: none;
  }
  .back-link:hover {
    color: var(--text);
    text-decoration: underline;
  }
  .head {
    margin-bottom: var(--space-xl);
  }
  .head h1 {
    font-family: var(--font-heading);
    font-size: var(--h2-size);
    margin: 0 0 0.5rem;
    letter-spacing: 0;
  }
  .lede {
    color: var(--text-secondary);
    margin: 0;
    font-size: var(--body-size);
  }
  .meta {
    color: var(--text-light);
    font-family: var(--font-mono);
    font-size: var(--small-size);
    margin: 0.25rem 0 0;
  }
  code {
    font-family: var(--font-mono);
    font-size: 0.95em;
    color: var(--marigold);
  }

  .section {
    margin-bottom: var(--space-xl);
  }
  .section h2 {
    font-family: var(--font-heading);
    font-size: 1.25rem;
    margin: 0 0 var(--space-sm);
  }

  .muted {
    color: var(--text-light);
    margin: 0 0 0.75rem;
  }

  .detected {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: 6px;
  }
  .detected li {
    padding: 10px 14px;
    border: 1px solid var(--border-light);
    border-radius: 0;
    background: var(--surface);
    font-size: var(--small-size);
    display: grid;
    grid-template-columns: 1fr auto;
    gap: 12px;
    align-items: center;
  }
  .selector {
    color: var(--text-light);
    font-size: 12px;
  }

  .available {
    list-style: none;
    margin: 0;
    padding: 0;
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
    gap: var(--space-md);
  }
  .cap-card {
    padding: 14px 16px;
    border: 1px solid var(--border-light);
    border-radius: 0;
    background: var(--surface);
  }
  .cap-card h3 {
    margin: 0 0 0.25rem;
    font-size: 1rem;
    font-weight: 600;
  }
  .cap-card p {
    margin: 0 0 0.5rem;
    font-size: var(--small-size);
    color: var(--text-secondary);
    line-height: 1.5;
  }
  .cap-card a {
    color: var(--sunset);
    font-size: var(--small-size);
    font-weight: 500;
  }
  .cap-card a:hover { text-decoration: underline; }

  textarea {
    width: 100%;
    font-family: var(--font-mono);
    font-size: var(--type-body-mobile, 16px);
    padding: 12px;
    border: 1px solid var(--border);
    border-radius: 0;
    background: var(--surface);
    color: var(--text);
    resize: vertical;
    min-height: 280px;
  }
  textarea:focus {
    outline: none;
    border-color: var(--sunset);
  }

  .error {
    color: var(--danger);
    font-size: var(--small-size);
    margin: 8px 0 0;
  }
  .ok {
    color: var(--sage-leaf);
    font-size: var(--small-size);
    margin: 8px 0 0;
  }
  .warn {
    color: var(--danger);
    font-size: var(--small-size);
    margin: 8px 0 0;
  }

  .actions {
    display: flex;
    gap: 0.5rem;
    margin-top: 12px;
  }
  .btn {
    padding: 0.5rem 1rem;
    border-radius: 0;
    font-size: var(--small-size);
    font-weight: 500;
    cursor: pointer;
    border: 1px solid transparent;
  }
  .btn:disabled { opacity: 0.6; cursor: not-allowed; }
  .btn.primary {
    background: var(--sunset);
    color: var(--bg-pure);
  }
  .btn.primary:hover:not(:disabled) { background: var(--sunset-hover); }
  .btn.secondary {
    background: transparent;
    color: var(--text);
    border-color: var(--border);
  }
  .btn.secondary:hover:not(:disabled) { border-color: var(--text-secondary); }
</style>
