// apps/web/app/docs/page.tsx
import Link from 'next/link';
import { SiteNav } from '../components/site-nav';

export const runtime = 'nodejs';

export const metadata = {
  title: 'Docs — Shippie',
  description:
    'Everything you need to ship an app on Shippie. Quick start, core concepts, the CLI, the SDK, and the platform under the hood.',
};

const SECTIONS = [
  {
    id: 'quickstart',
    title: 'Quick start',
    blurb: 'Ship something in 60 seconds — pick the surface that matches where your code is.',
  },
  {
    id: 'concepts',
    title: 'Core concepts',
    blurb: 'App types, deploys, install funnels, ratings, leaderboards — the vocabulary of the marketplace.',
  },
  {
    id: 'cli',
    title: 'CLI',
    blurb: '`shippie init`, `shippie deploy`, `shippie link`. A Bun-native CLI that treats the marketplace like git.',
  },
  {
    id: 'sdk',
    title: 'SDK',
    blurb: '`@shippie/sdk/wrapper` — 42 runtime exports for PWA installs, push, ratings, offline, and analytics.',
  },
  {
    id: 'platform',
    title: 'Platform',
    blurb: 'Cloudflare Workers runtime, Postgres control plane, signed webhook spine. The parts that run your apps.',
  },
];

export default function DocsPage() {
  return (
    <div className="grain">
      <SiteNav />
      <main
        style={{
          maxWidth: 880,
          margin: '0 auto',
          padding: 'var(--space-xl)',
          paddingTop: 'calc(var(--nav-height) + var(--safe-top) + var(--space-xl))',
          paddingBottom: 'var(--space-3xl)',
        }}
      >
        <header style={{ marginBottom: 'var(--space-2xl)' }}>
          <p className="eyebrow">Documentation</p>
          <h1
            style={{
              fontFamily: 'var(--font-heading)',
              fontSize: 'clamp(2.2rem, 5vw, 3.4rem)',
              letterSpacing: '-0.02em',
              margin: '0.25rem 0 var(--space-md)',
              lineHeight: 1.05,
            }}
          >
            Ship an app on Shippie.
          </h1>
          <p style={{ fontSize: 'var(--body-size)', color: 'var(--text-secondary)', lineHeight: 1.6, maxWidth: 620 }}>
            Shippie turns a git repo into an installable PWA on a marketplace in under a minute.
            The guides below cover everything from the first deploy to the runtime internals —
            pick whichever page is the shortest path to what you&apos;re trying to do.
          </p>
        </header>

        <nav
          aria-label="Docs sections"
          style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 'var(--space-md)', marginBottom: 'var(--space-3xl)' }}
        >
          {SECTIONS.map((s) => (
            <a key={s.id} href={`#${s.id}`} className="card" style={{ padding: 'var(--space-md)' }}>
              <p className="eyebrow" style={{ marginBottom: 4 }}>{s.title}</p>
              <p style={{ color: 'var(--text-secondary)', fontSize: 'var(--small-size)', lineHeight: 1.5, margin: 0 }}>
                {s.blurb}
              </p>
            </a>
          ))}
        </nav>

        <Section id="quickstart" title="Quick start">
          <p>Four paths, same result. Pick the shortest one for your codebase.</p>
          <Subsection title="Wrap an already-hosted app">
            <p>
              App already on Vercel, Netlify, Render, or your own server? Don&apos;t move
              it. Shippie adds a marketplace entry + PWA shell + install funnel, served
              via edge reverse-proxy at <code>{'{slug}'}.shippie.app</code>. Your backend
              stays where it runs best.
            </p>
            <Code
              lines={[
                'shippie wrap https://mevrouw.vercel.app --slug mevrouw',
                '',
                '# → live at https://mevrouw.shippie.app/',
                '# → Supabase/Auth0/Clerk: add this redirect URI:',
                '#   https://mevrouw.shippie.app/api/auth/callback',
              ]}
            />
            <p>
              Works with any PWA that responds over HTTPS: Next.js, Astro, Remix, Nuxt,
              Rails, Django, Go — anything.
            </p>
          </Subsection>
          <Subsection title="From a git repo (recommended)">
            <p>
              Install the GitHub App and point it at a repo. Shippie detects the framework, builds
              it on every push, and publishes an installable app to your slug. No Vercel account,
              no separate hosting, no App Store review.
            </p>
            <Link href="/new" className="btn-primary" style={{ marginTop: 'var(--space-sm)' }}>
              Connect a repo →
            </Link>
          </Subsection>
          <Subsection title="From your terminal">
            <Code
              lines={[
                '# one-time: authenticate the CLI',
                'bunx shippie login',
                '',
                '# from your project root',
                'shippie init   # detect framework, scaffold config',
                'shippie deploy # build + publish',
              ]}
            />
          </Subsection>
          <Subsection title="From the web">
            <p>
              Paste a GitHub URL at <Link href="/new">/new</Link>. Shippie handles the OAuth, the
              build, and the slug assignment. Useful when you&apos;re deploying from a phone or a
              Chromebook.
            </p>
          </Subsection>
        </Section>

        <Section id="concepts" title="Core concepts">
          <Concept name="App type">
            Every app is <code>app</code>, <code>web_app</code>, or <code>website</code>. The
            shelves on the home page and the default layouts (bottom tabs vs. top nav) come from
            this classification. Changeable at any time from the dashboard.
          </Concept>
          <Concept name="Deploy">
            A frozen, reproducible build of your app at a git SHA. Every push to the tracked branch
            creates a new deploy. Only the <code>active_deploy_id</code> on an app record is what
            users install — the rest are hot-standby for instant rollback.
          </Concept>
          <Concept name="Install funnel">
            Shippie measures <code>install_prompt_shown</code>,
            <code>install_prompt_accepted</code>, and first-session opens. These feed the
            trending shelf on <Link href="/leaderboards">/leaderboards</Link> and the funnel cards
            on your dashboard.
          </Concept>
          <Concept name="Rating">
            A 1–5 score with optional text review, bound to an installed device. The top-rated
            leaderboard requires at least three ratings so a single-star troll doesn&apos;t own the
            shelf.
          </Concept>
          <Concept name="Slug">
            Your URL, marketplace handle, and rating namespace all share one slug. Claim once,
            yours forever — transferable between repos from the dashboard.
          </Concept>
        </Section>

        <Section id="cli" title="CLI">
          <p>
            The CLI is a thin wrapper around the marketplace API — no hidden state, one config
            file (<code>shippie.toml</code>), readable output. Install with:
          </p>
          <Code lines={['bun add -g @shippie/cli', '# or', 'npm i -g @shippie/cli']} />
          <DefList
            rows={[
              ['shippie login', 'Device-code flow. Writes a token to ~/.shippie/auth.json.'],
              ['shippie init', 'Detect framework, scaffold shippie.toml, write .gitignore entries.'],
              ['shippie link', 'Attach a repo to an existing slug — swap between local directories without losing history.'],
              ['shippie deploy', 'Build + publish + activate. Skip build if SHA is already deployed.'],
              ['shippie rollback', 'Flip the active_deploy_id to a previous deploy. Instant, no rebuild.'],
              ['shippie logs', 'Tail runtime + build logs from the Worker.'],
            ]}
          />
        </Section>

        <Section id="sdk" title="SDK">
          <p>
            <code>@shippie/sdk/wrapper</code> is a framework-agnostic runtime for PWA behaviour
            and platform integration. It&apos;s installed automatically on every deploy, but you
            can opt into pieces of it directly:
          </p>
          <Code
            lines={[
              "import { enableInstallPrompt, subscribeToPush, postRating } from '@shippie/sdk/wrapper';",
              '',
              'await enableInstallPrompt({ onAccept: () => track("install") });',
              'await subscribeToPush({ topics: ["updates"] });',
              'await postRating({ score: 5, body: "ships on my phone, worth it" });',
            ]}
          />
          <DefList
            rows={[
              ['Install prompt', 'Cross-browser install funnel — native where supported, iOS Chrome guide where it isn\'t.'],
              ['Push', 'VAPID-signed Web Push with topic subscriptions. Fanout lives in the control plane.'],
              ['Ratings', 'Installed-device-bound ratings, one per user per app, optimistic UI.'],
              ['Offline', 'Opinionated service-worker runtime caches + background sync queues for POSTs.'],
              ['Analytics', 'Trace-id-tagged events to /api/ingest — the same pipeline that powers leaderboards.'],
            ]}
          />
        </Section>

        <Section id="platform" title="Platform">
          <p>
            Apps run on Cloudflare Workers. Metadata, ratings, sessions, deploys, and webhook state
            live in Postgres 16. The two are stitched by a signed-request spine so every
            API call from a Worker to the control plane is authenticated end-to-end.
          </p>
          <DefList
            rows={[
              ['Runtime', 'Cloudflare Worker per app, one KV namespace for static assets, Durable Objects for rate limits.'],
              ['Control plane', 'Next.js 16 on Vercel, Postgres 16, Drizzle ORM, Auth.js magic links.'],
              ['Install attribution', 'Signed short-lived token on the install prompt so accepts can\'t be spoofed.'],
              ['Rollback', 'Active deploy id is a single column swap. No DNS, no cache warmup.'],
              ['Limits', '300s function timeout, 4MB request body, 25MB per deploy. Lift with a support request.'],
            ]}
          />
        </Section>

        <footer
          style={{
            marginTop: 'var(--space-3xl)',
            paddingTop: 'var(--space-xl)',
            borderTop: '1px solid var(--border-light)',
            display: 'flex',
            flexWrap: 'wrap',
            gap: 'var(--space-md)',
            justifyContent: 'space-between',
            color: 'var(--text-light)',
            fontFamily: 'var(--font-mono)',
            fontSize: 13,
          }}
        >
          <span>Missing something? File an issue on{' '}
            <a href="https://github.com/shippie/shippie" style={{ color: 'var(--sunset)' }}>
              github.com/shippie/shippie
            </a>.
          </span>
          <span>v0.1 — docs are a work in progress</span>
        </footer>
      </main>
    </div>
  );
}

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} style={{ marginBottom: 'var(--space-3xl)', scrollMarginTop: 'calc(var(--nav-height) + var(--safe-top) + 20px)' }}>
      <h2
        style={{
          fontFamily: 'var(--font-heading)',
          fontSize: 'clamp(1.6rem, 3vw, 2.2rem)',
          letterSpacing: '-0.02em',
          paddingBottom: 'var(--space-sm)',
          borderBottom: '1px solid var(--border-light)',
          marginBottom: 'var(--space-lg)',
        }}
      >
        {title}
      </h2>
      <div className="docs-prose" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-md)' }}>
        {children}
      </div>
    </section>
  );
}

function Subsection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginTop: 'var(--space-sm)' }}>
      <h3 style={{ fontWeight: 600, fontSize: 'var(--body-size)', margin: '0 0 var(--space-sm)' }}>{title}</h3>
      {children}
    </div>
  );
}

function Concept({ name, children }: { name: string; children: React.ReactNode }) {
  return (
    <div
      style={{
        display: 'grid',
        gridTemplateColumns: 'minmax(120px, 180px) 1fr',
        gap: 'var(--space-lg)',
        paddingBottom: 'var(--space-md)',
        borderBottom: '1px dashed var(--border-light)',
      }}
      className="docs-concept-row"
    >
      <div style={{ fontFamily: 'var(--font-mono)', fontSize: 13, color: 'var(--sunset)', letterSpacing: '0.02em' }}>
        {name}
      </div>
      <div style={{ color: 'var(--text-secondary)', lineHeight: 1.6 }}>{children}</div>
    </div>
  );
}

function DefList({ rows }: { rows: [string, string][] }) {
  return (
    <dl
      style={{
        display: 'grid',
        gridTemplateColumns: 'minmax(140px, 220px) 1fr',
        gap: 'var(--space-sm) var(--space-lg)',
        margin: 'var(--space-sm) 0 0',
      }}
    >
      {rows.map(([k, v]) => (
        <div key={k} style={{ display: 'contents' }}>
          <dt style={{ fontFamily: 'var(--font-mono)', fontSize: 13, color: 'var(--text-primary)' }}>{k}</dt>
          <dd style={{ color: 'var(--text-secondary)', margin: 0, lineHeight: 1.5 }}>{v}</dd>
        </div>
      ))}
    </dl>
  );
}

function Code({ lines }: { lines: string[] }) {
  return (
    <pre
      style={{
        background: 'var(--surface)',
        border: '1px solid var(--border-light)',
        padding: 'var(--space-md)',
        fontFamily: 'var(--font-mono)',
        fontSize: 13,
        color: 'var(--text-primary)',
        overflow: 'auto',
        lineHeight: 1.6,
      }}
    >
      <code>{lines.join('\n')}</code>
    </pre>
  );
}

// apps/platform/src/routes/docs/+page.svelte
<script lang="ts">
  // Minimal docs landing — structure ported from apps/web/app/docs/page.tsx,
  // copy lifted verbatim where the source had it. Each section is a stub:
  // 2-3 paragraphs, polish in a follow-up.
  const sections = [
    {
      id: 'getting-started',
      title: 'Getting started',
      blurb: 'Ship something in 60 seconds — pick the surface that matches where your code is.',
    },
    {
      id: 'sdk',
      title: 'SDK',
      blurb: '@shippie/sdk/wrapper — runtime exports for PWA installs, push, ratings, offline, and analytics.',
    },
    {
      id: 'wrapper',
      title: 'Wrapper',
      blurb: 'The HTML rewriter that injects the manifest, service worker, and SDK at the edge.',
    },
    {
      id: 'local-runtime',
      title: 'Local Runtime',
      blurb: 'Run apps locally against the same edge worker. Zero-cost dev loop with real bindings.',
    },
    {
      id: 'self-hosting',
      title: 'Self-hosting',
      blurb: 'Run your own instance. AGPL-3.0. No vendor lock-in.',
    },
    {
      id: 'auto-deploys',
      title: 'GitHub auto-deploys',
      blurb: 'Connect a repo — we clone and build on every push. Honestly slower than zip uploads.',
    },
  ];
</script>

<svelte:head>
  <title>Docs — Shippie</title>
  <meta
    name="description"
    content="Everything you need to ship an app on Shippie. Getting started, the SDK, the wrapper, the local runtime, and self-hosting."
  />
</svelte:head>

<main class="docs-page">
  <header class="head">
    <p class="eyebrow">
      <img src="/__shippie-pwa/icon.svg" alt="" width="14" height="14" />
      Documentation
    </p>
    <h1 class="title">Ship an app on Shippie.</h1>
    <p class="lede">
      Shippie turns a git repo (or a zip, or a URL) into an installable PWA on a marketplace in
      under a minute. The sections below cover everything from the first deploy to the runtime
      internals — pick whichever is the shortest path to what you're trying to do.
    </p>
  </header>

  <nav class="nav-cards" aria-label="Docs sections">
    {#each sections as s (s.id)}
      <a href={`#${s.id}`} class="nav-card">
        <p class="card-eyebrow">{s.title}</p>
        <p class="card-blurb">{s.blurb}</p>
      </a>
    {/each}
  </nav>

  <section id="getting-started" class="section">
    <h2>Getting started</h2>
    <p>
      Four paths, same result. Pick the shortest one for your codebase.
    </p>
    <h3>Wrap an already-hosted app</h3>
    <p>
      App already hosted somewhere else? Don't move it. Shippie adds a
      marketplace entry, a PWA shell, and an install funnel via edge reverse-proxy at
      <code>{'{slug}'}.shippie.app</code>. Your backend stays where it runs best.
    </p>
    <pre class="code">shippie wrap https://your-app.example.com --slug your-app

# → live at https://your-app.shippie.app/</pre>
    <h3>Drop a zip in the browser</h3>
    <p>
      Visit <a href="/new">/new</a> and drag a zip of your built site into the drop zone. We unpack
      it to R2, register the slug, wire up the wrapper, and the URL goes live in under a minute.
    </p>
    <h3>Push from the CLI</h3>
    <p>
      <code>shippie ship</code> from any project directory. Detects the build output, zips it, and
      uploads with the same 60-second SLA as the web flow.
    </p>
    <h3>Connect a GitHub repo</h3>
    <p>
      For automated builds on every push. We clone, install, build, and upload — typically in 2–5
      minutes. Slower than zip uploads, but you don't have to think about it.
    </p>
  </section>

  <section id="sdk" class="section">
    <h2>SDK</h2>
    <p>
      <code>@shippie/sdk/wrapper</code> is the runtime injected into every Shippie-hosted page. It
      provides install prompts, push subscriptions, ratings UI, offline coordination, and a
      structured event spine that flows back to the marketplace.
    </p>
    <p>
      Every export is opt-in. The base wrapper is &lt;5kb gzipped. Add features by importing them.
    </p>
    <p>
      The SDK reference moves here in a follow-up — until then, the README in
      <a href="https://github.com/shippie/shippie/tree/main/packages/sdk">packages/sdk</a> is the
      source of truth.
    </p>
  </section>

  <section id="wrapper" class="section">
    <h2>Wrapper</h2>
    <p>
      The wrapper is the HTML rewriter that runs at the edge. It injects the PWA manifest, the
      service worker registration, the SDK runtime, and the install funnel — without touching your
      bundled code.
    </p>
    <p>
      Wrapper config lives in a tiny <code>shippie.json</code> at the root of your deploy. App name,
      theme color, icon path, and any opt-in capability flags. We have sensible defaults for every
      field.
    </p>
  </section>

  <section id="local-runtime" class="section">
    <h2>Local Runtime</h2>
    <p>
      The same edge worker runs locally via <code>wrangler dev</code>. D1 has a local SQLite mode,
      R2 has a filesystem-backed mode, KV has an in-memory mode. Your dev loop hits the same
      bindings the production worker does.
    </p>
    <p>
      No Docker, no cloud round-trips, no separate dev server. Run <code>bun dev</code> in
      <code>apps/platform/</code> and you're testing against the real wrapper.
    </p>
  </section>

  <section id="self-hosting" class="section">
    <h2>Self-hosting</h2>
    <p>
      Shippie is AGPL-3.0. The whole platform — control plane, edge worker, SDK, CLI — is on
      GitHub at <a href="https://github.com/shippie/shippie">shippie/shippie</a>. Fork it, deploy
      it, run it on your own Cloudflare account.
    </p>
    <p>
      You'll need a Cloudflare account, a domain you control, and the patience to register OAuth
      clients with GitHub and (optionally) Google. The hosted Shippie costs $5–10/month at our
      scale; your bill will be similar or smaller depending on traffic.
    </p>
  </section>

  <section id="auto-deploys" class="section">
    <h2>GitHub auto-deploys (the honest version)</h2>
    <p>
      Connect a GitHub repo to a Shippie app and every push triggers a build. We clone the repo on
      a fresh GitHub Actions runner, install dependencies, run your build script, and upload the
      output to R2.
    </p>
    <p>
      Typical end-to-end time: <strong>2–5 minutes</strong>. The cold runner is the floor; npm
      install variance is the spread. We don't claim sub-60-second auto-deploys — that path is the
      direct zip upload, where there's no clone or install to do.
    </p>
    <p>
      If you need 60-second deploys for a GitHub-tracked project, set up a CI step that ships the
      built artifact via <code>shippie ship</code>. Same speed as the web upload.
    </p>
  </section>
</main>

<style>
  .docs-page {
    max-width: 880px;
    margin: 0 auto;
    padding: var(--space-2xl) clamp(1.5rem, 4vw, 3rem) var(--space-3xl);
  }
  .head { margin-bottom: var(--space-2xl); }
  .eyebrow {
    display: inline-flex;
    align-items: center;
    gap: 0.4rem;
    font-family: var(--font-mono);
    font-size: var(--caption-size);
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: var(--text-light);
    margin: 0;
  }
  .eyebrow img { display: block; }
  .title {
    font-family: var(--font-heading);
    font-size: clamp(2.2rem, 5vw, 3.4rem);
    letter-spacing: -0.02em;
    margin: 0.25rem 0 var(--space-md);
    line-height: 1.05;
  }
  .lede {
    font-size: var(--body-size);
    color: var(--text-secondary);
    line-height: 1.6;
    max-width: 620px;
    margin: 0;
  }

  .nav-cards {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
    gap: var(--space-md);
    margin-bottom: var(--space-3xl);
  }
  .nav-card {
    padding: var(--space-md);
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 0;
    color: var(--text);
    transition: border-color 0.2s;
  }
  .nav-card:hover { border-color: var(--sunset); }
  .card-eyebrow {
    font-family: var(--font-mono);
    font-size: var(--caption-size);
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: var(--text-light);
    margin: 0 0 4px;
  }
  .card-blurb {
    color: var(--text-secondary);
    font-size: var(--small-size);
    line-height: 1.5;
    margin: 0;
  }

  .section {
    margin-bottom: var(--space-2xl);
    padding-top: var(--space-xl);
    border-top: 1px solid var(--border-light);
  }
  .section h2 {
    font-family: var(--font-heading);
    font-size: 1.75rem;
    letter-spacing: -0.01em;
    margin: 0 0 var(--space-md);
  }
  .section h3 {
    font-family: var(--font-heading);
    font-size: 1.125rem;
    margin: var(--space-lg) 0 var(--space-xs);
  }
  .section p {
    color: var(--text-secondary);
    line-height: 1.7;
    margin: 0 0 var(--space-md);
  }
  .section a {
    color: var(--sunset);
    text-decoration: underline;
    text-underline-offset: 2px;
  }
  .section code {
    font-family: var(--font-mono);
    font-size: 0.92em;
    background: var(--surface);
    padding: 1px 6px;
    border: 1px solid var(--border-light);
  }
  .code {
    background: var(--bg-pure);
    border: 1px solid var(--border-light);
    border-radius: 0;
    padding: var(--space-md);
    font-family: var(--font-mono);
    font-size: 0.9rem;
    line-height: 1.7;
    overflow-x: auto;
    color: var(--text);
  }
</style>
