// apps/platform/src/routes/new/upload-form.svelte
<script lang="ts" module>
  function formatBytes(n: number): string {
    if (n < 1024) return `${n}B`;
    if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)}KB`;
    return `${(n / (1024 * 1024)).toFixed(1)}MB`;
  }
</script>

<script lang="ts">
  type Result =
    | { kind: 'idle' }
    | { kind: 'submitting' }
    | {
        kind: 'success';
        slug: string;
        liveUrl: string;
        deployId?: string;
        version?: number;
        files?: number;
        totalBytes?: number;
        preflightMs?: number;
      }
    | { kind: 'error'; reason: string; blockers?: Array<{ rule: string; title: string; detail?: string }> };

  let slug = $state('recipes');
  let file = $state<File | null>(null);
  let result = $state<Result>({ kind: 'idle' });
  let visibility = $state<'public' | 'unlisted' | 'private'>('public');
  let copied = $state(false);

  const shareUrl = $derived(
    result.kind === 'success'
      ? visibility === 'private'
        ? `(generating private invite — open the dashboard)`
        : `${typeof window !== 'undefined' ? window.location.origin : ''}/apps/${result.slug}`
      : '',
  );

  async function handleSubmit(ev: SubmitEvent) {
    ev.preventDefault();
    if (!file || !slug) return;
    result = { kind: 'submitting' };

    const fd = new FormData();
    fd.append('slug', slug);
    fd.append('zip', file);

    try {
      const res = await fetch('/api/deploy', { method: 'POST', body: fd });
      const j = (await res.json().catch(() => ({}))) as Record<string, unknown>;
      if (res.ok && j.success) {
        result = {
          kind: 'success',
          slug: String(j.slug),
          liveUrl: String(j.live_url),
          deployId: typeof j.deploy_id === 'string' ? j.deploy_id : undefined,
          version: typeof j.version === 'number' ? j.version : undefined,
          files: typeof j.files === 'number' ? j.files : undefined,
          totalBytes: typeof j.total_bytes === 'number' ? j.total_bytes : undefined,
          preflightMs:
            typeof (j.preflight as { duration_ms?: number })?.duration_ms === 'number'
              ? (j.preflight as { duration_ms: number }).duration_ms
              : undefined,
        };
      } else {
        result = {
          kind: 'error',
          reason: String(j.reason ?? j.error ?? 'Deploy failed.'),
          blockers: (
            j.preflight as { blockers?: Array<{ rule: string; title: string; detail?: string }> } | undefined
          )?.blockers,
        };
      }
    } catch (err) {
      result = { kind: 'error', reason: err instanceof Error ? err.message : String(err) };
    }
  }

  function handleFile(e: Event) {
    const t = e.target as HTMLInputElement;
    file = t.files?.[0] ?? null;
  }

  async function patchVisibility(next: 'public' | 'unlisted' | 'private') {
    if (result.kind !== 'success') return;
    const res = await fetch(`/api/apps/${encodeURIComponent(result.slug)}/visibility`, {
      method: 'PATCH',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ visibility_scope: next }),
    });
    if (res.ok) visibility = next;
  }

  async function onCopy() {
    if (!shareUrl) return;
    try {
      await navigator.clipboard.writeText(shareUrl);
      copied = true;
      setTimeout(() => (copied = false), 1500);
    } catch {
      // clipboard unavailable — silent
    }
  }
</script>

<form onsubmit={handleSubmit} class="form">
  <label>
    <span class="label">Slug</span>
    <div class="slug-row">
      <input bind:value={slug} pattern="[a-z0-9][a-z0-9\-]*" required class="slug-input" />
      <span class="suffix">.shippie.app</span>
    </div>
  </label>

  <label>
    <span class="label">Zip (built output)</span>
    <input type="file" accept=".zip,application/zip" onchange={handleFile} required class="file-input" />
  </label>

  <button type="submit" disabled={result.kind === 'submitting' || !file || !slug} class="btn-primary">
    {result.kind === 'submitting' ? 'Shipping…' : 'Ship it →'}
  </button>

  {#if result.kind === 'success'}
    <div class="success">
      <p class="success-head">✓ Shipped{result.version ? ` — v${result.version}` : ''}</p>
      <p>
        Live at
        <a href={result.liveUrl} target="_blank" rel="noreferrer">{result.liveUrl}</a>
      </p>
      {#if result.deployId}
        <p>
          Review the
          <a href={`/dashboard/apps/${result.slug}/deploys/${result.deployId}`}>deploy intelligence report</a>
        </p>
      {/if}

      <div class="share-card">
        <div class="share-head">
          <p>Share this app</p>
          <div class="vis-toggle" role="radiogroup" aria-label="Visibility">
            {#each ['public', 'unlisted', 'private'] as v (v)}
              <button
                type="button"
                class:active={visibility === v}
                onclick={() => patchVisibility(v as 'public' | 'unlisted' | 'private')}>{v}</button>
            {/each}
          </div>
        </div>
        <div class="share-row">
          <input type="text" readonly value={shareUrl} class="share-input" />
          <button type="button" onclick={onCopy} class="copy-btn">{copied ? 'Copied' : 'Copy'}</button>
        </div>
      </div>

      {#if result.files != null || result.totalBytes != null || result.preflightMs != null}
        <p class="meta">
          {#if result.files != null}{result.files} files · {/if}
          {#if result.totalBytes != null}{formatBytes(result.totalBytes)} · {/if}
          {#if result.preflightMs != null}preflight {result.preflightMs}ms{/if}
        </p>
      {/if}
    </div>
  {:else if result.kind === 'error'}
    <div class="error">
      <p class="error-head">✗ {result.reason}</p>
      {#if result.blockers && result.blockers.length > 0}
        <ul>
          {#each result.blockers as b (b.rule + b.title)}
            <li>
              <strong>{b.title}</strong>
              {#if b.detail}
                <span>{b.detail}</span>
              {/if}
            </li>
          {/each}
        </ul>
      {/if}
    </div>
  {/if}
</form>

<style>
  .form { display: flex; flex-direction: column; gap: 1rem; }
  .label {
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.16em;
    color: #8B847A;
    font-family: ui-monospace, monospace;
  }
  .slug-row { display: flex; align-items: stretch; margin-top: 0.25rem; }
  .slug-input {
    flex: 1;
    height: 44px;
    padding: 0 0.75rem;
    border: 1px solid #C9C2B1;
    background: transparent;
    font-family: ui-monospace, monospace;
    font-size: 14px;
    color: inherit;
    border-radius: 0;
    box-sizing: border-box;
  }
  .slug-input:focus { border-color: #E8603C; outline: none; }
  .suffix {
    height: 44px;
    line-height: 44px;
    padding: 0 0.75rem;
    border: 1px solid #C9C2B1;
    border-left: none;
    background: rgba(0,0,0,0.02);
    font-family: ui-monospace, monospace;
    font-size: 14px;
    color: #8B847A;
    border-radius: 0 8px 8px 0;
  }
  .file-input { margin-top: 0.25rem; }
  .btn-primary {
    height: 48px;
    background: #E8603C;
    color: white;
    border: none;
    padding: 0 2rem;
    border-radius: 0;
    font-weight: 700;
    font-size: 15px;
    cursor: pointer;
    align-self: flex-start;
  }
  .btn-primary:disabled { opacity: 0.5; cursor: not-allowed; }
  .success {
    padding: 1rem 1.25rem;
    border: 1px solid rgba(46,125,91,0.4);
    background: rgba(46,125,91,0.05);
    border-radius: 0;
    color: #2E7D5B;
  }
  .success-head { font-weight: 700; margin: 0; }
  .success a { color: inherit; font-family: ui-monospace, monospace; }
  .meta { font-family: ui-monospace, monospace; font-size: 11px; color: #8B847A; margin: 0.5rem 0 0 0; }
  .share-card { margin-top: 0.75rem; padding: 0.75rem; background: rgba(255,255,255,0.5); border-radius: 0; }
  .share-head { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem; }
  .share-head p { font-size: 12px; color: #14120F; margin: 0; font-weight: 600; }
  .vis-toggle { display: inline-flex; gap: 2px; padding: 2px; background: rgba(0,0,0,0.05); border-radius: 0; }
  .vis-toggle button {
    background: transparent;
    border: none;
    padding: 4px 10px;
    border-radius: 0;
    font-size: 11px;
    font-family: ui-monospace, monospace;
    cursor: pointer;
    color: #8B847A;
  }
  .vis-toggle button.active { background: #2E7D5B; color: white; }
  .share-row { display: flex; gap: 6px; }
  .share-input {
    flex: 1;
    height: 36px;
    padding: 0 0.625rem;
    font-family: ui-monospace, monospace;
    font-size: 12px;
    background: white;
    border: 1px solid #C9C2B1;
    border-radius: 0;
    box-sizing: border-box;
    color: inherit;
  }
  .copy-btn {
    height: 36px;
    padding: 0 0.875rem;
    background: transparent;
    border: 1px solid #C9C2B1;
    border-radius: 0;
    font-size: 12px;
    cursor: pointer;
    color: inherit;
  }
  .error {
    padding: 1rem 1.25rem;
    border: 1px solid rgba(180,63,42,0.4);
    background: rgba(180,63,42,0.05);
    border-radius: 0;
    color: #B43F2A;
  }
  .error-head { font-weight: 700; margin: 0; }
  .error ul { margin: 0.5rem 0 0 1.25rem; padding: 0; font-family: ui-monospace, monospace; font-size: 12px; }
  .error li + li { margin-top: 0.375rem; }
  .error li span { display: block; margin-top: 0.125rem; color: rgba(180,63,42,0.78); }
  @media (prefers-color-scheme: dark) {
    .slug-input, .suffix, .share-input, .copy-btn { border-color: #3A352D; }
    .suffix { background: rgba(255,255,255,0.03); }
    .share-card { background: rgba(255,255,255,0.04); }
    .share-head p { color: #EDE4D3; }
    .vis-toggle { background: rgba(255,255,255,0.05); }
    .share-input { background: #1F1B16; }
  }
</style>

// apps/web/app/new/upload-form.tsx
/**
 * Client component: upload zip + POST to /api/deploy.
 *
 * Spec v6 §1 (onboarding flow), §10 (deploy pipeline).
 */
'use client';

import { useState } from 'react';

interface DeployResponse {
  success: boolean;
  slug?: string;
  version?: number;
  files?: number;
  total_bytes?: number;
  live_url?: string;
  error?: string;
  reason?: string;
  preflight?: {
    passed: boolean;
    blockers?: Array<{ rule: string; title: string }>;
    warnings?: Array<{ rule: string; title: string }>;
    duration_ms?: number;
  };
}

export function UploadForm() {
  const [slug, setSlug] = useState('recipes');
  const [file, setFile] = useState<File | null>(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<DeployResponse | null>(null);

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!file || !slug) return;

    setLoading(true);
    setResult(null);

    const formData = new FormData();
    formData.append('slug', slug);
    formData.append('zip', file);

    try {
      const res = await fetch('/api/deploy', { method: 'POST', body: formData });
      const json = (await res.json()) as DeployResponse;
      setResult(json);
    } catch (err) {
      setResult({
        success: false,
        error: 'network_error',
        reason: err instanceof Error ? err.message : String(err),
      });
    } finally {
      setLoading(false);
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-5">
      <label className="block">
        <span className="text-xs uppercase tracking-widest text-neutral-500 font-mono">
          Slug
        </span>
        <div className="flex items-center mt-1">
          <input
            name="slug"
            value={slug}
            onChange={(e) => setSlug(e.target.value)}
            pattern="[a-z0-9][a-z0-9\-]*"
            required
            className="flex-1 block h-11 rounded-l-md border border-neutral-300 dark:border-neutral-700 bg-transparent px-3 font-mono text-sm focus:border-brand-500 outline-none"
          />
          <span className="inline-flex h-11 items-center px-3 rounded-r-md border border-l-0 border-neutral-300 dark:border-neutral-700 text-neutral-500 font-mono text-sm">
            .shippie.app
          </span>
        </div>
      </label>

      <label className="block">
        <span className="text-xs uppercase tracking-widest text-neutral-500 font-mono">
          Zip (built output)
        </span>
        <input
          type="file"
          accept=".zip,application/zip"
          onChange={(e) => setFile(e.target.files?.[0] ?? null)}
          required
          className="mt-1 block w-full text-sm file:mr-3 file:h-11 file:px-4 file:rounded-md file:border file:border-neutral-300 dark:file:border-neutral-700 file:bg-transparent file:text-neutral-700 dark:file:text-neutral-300 file:font-medium hover:file:border-brand-500 transition-colors"
        />
      </label>

      <button
        type="submit"
        disabled={loading || !file || !slug}
        className="inline-flex h-12 items-center rounded-full bg-brand-500 px-8 text-white font-medium hover:bg-brand-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {loading ? 'Shipping…' : 'Ship it →'}
      </button>

      {result && <ResultCard result={result} />}
    </form>
  );
}

function ResultCard({ result }: { result: DeployResponse }) {
  if (result.success && result.live_url) {
    return (
      <div className="rounded-lg border border-emerald-500/40 bg-emerald-50 dark:bg-emerald-950/30 p-4 space-y-2">
        <p className="text-sm font-semibold text-emerald-700 dark:text-emerald-200">
          ✅ Shipped — v{result.version}
        </p>
        <p className="text-sm">
          Live at{' '}
          <a
            href={result.live_url}
            target="_blank"
            rel="noreferrer"
            className="font-mono text-emerald-700 dark:text-emerald-300 underline"
          >
            {result.live_url}
          </a>
        </p>
        <p className="text-xs text-neutral-500 font-mono">
          {result.files} files · {formatBytes(result.total_bytes ?? 0)} · preflight{' '}
          {result.preflight?.duration_ms ?? 0}ms
        </p>
      </div>
    );
  }

  return (
    <div className="rounded-lg border border-red-500/40 bg-red-50 dark:bg-red-950/30 p-4 space-y-2">
      <p className="text-sm font-semibold text-red-700 dark:text-red-200">
        ❌ {result.error ?? 'Deploy failed'}
      </p>
      {result.reason && (
        <p className="text-sm text-red-700 dark:text-red-200">{result.reason}</p>
      )}
      {result.preflight?.blockers && result.preflight.blockers.length > 0 && (
        <ul className="text-xs font-mono space-y-1 mt-2">
          {result.preflight.blockers.map((b, i) => (
            <li key={i} className="text-red-700 dark:text-red-200">
              <strong>{b.rule}</strong>: {b.title}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

function formatBytes(n: number): string {
  if (n < 1024) return `${n}B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)}KB`;
  return `${(n / (1024 * 1024)).toFixed(1)}MB`;
}
