// apps/platform/src/routes/new/wrap-form.svelte
<script lang="ts">
  type Phase =
    | { kind: 'idle' }
    | { kind: 'submitting' }
    | { kind: 'done'; slug: string; liveUrl: string; redirectUri: string }
    | { kind: 'error'; message: string };

  let phase = $state<Phase>({ kind: 'idle' });

  async function onSubmit(ev: SubmitEvent) {
    ev.preventDefault();
    const form = new FormData(ev.currentTarget as HTMLFormElement);
    phase = { kind: 'submitting' };

    const taglineRaw = String(form.get('tagline') ?? '');
    const body = {
      upstream_url: String(form.get('upstream_url') ?? ''),
      slug: String(form.get('slug') ?? ''),
      name: String(form.get('name') ?? ''),
      ...(taglineRaw ? { tagline: taglineRaw } : {}),
      type: String(form.get('type') ?? 'app'),
      category: String(form.get('category') ?? 'tools'),
    };

    const res = await fetch('/api/deploy/wrap', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(body),
    });
    const j = (await res.json().catch(() => ({}))) as {
      success?: boolean;
      slug?: string;
      live_url?: string;
      runtime_config?: { required_redirect_uris?: string[] };
      reason?: string;
      error?: string;
    };
    if (res.ok && j.success && j.live_url && j.slug) {
      phase = {
        kind: 'done',
        slug: j.slug,
        liveUrl: j.live_url,
        redirectUri: j.runtime_config?.required_redirect_uris?.[0] ?? '',
      };
    } else {
      phase = { kind: 'error', message: j.reason ?? j.error ?? 'Wrap failed.' };
    }
  }
</script>

{#if phase.kind === 'done'}
  <div class="success">
    <p class="head">✓ Wrapped</p>
    <p>
      Live at
      <a href={phase.liveUrl} target="_blank" rel="noreferrer">{phase.liveUrl}</a>
    </p>
    {#if phase.redirectUri}
      <p class="dim">Add this redirect URI to your auth provider:</p>
      <pre>{phase.redirectUri}</pre>
    {/if}
  </div>
{:else}
  <form onsubmit={onSubmit} class="form">
    <label>
      <span>Upstream URL</span>
      <input name="upstream_url" type="url" placeholder="https://mevrouw.vercel.app" required />
    </label>
    <label>
      <span>Slug</span>
      <input name="slug" placeholder="mevrouw" required pattern="[a-z0-9][a-z0-9-]*[a-z0-9]" />
    </label>
    <label>
      <span>Name</span>
      <input name="name" placeholder="Mevrouw" required />
    </label>
    <label>
      <span>Tagline (optional)</span>
      <input name="tagline" />
    </label>
    <div class="row">
      <label>
        <span>Type</span>
        <select name="type">
          <option value="app">App</option>
          <option value="web_app">Web app</option>
          <option value="website">Website</option>
        </select>
      </label>
      <label>
        <span>Category</span>
        <input name="category" placeholder="tools" value="tools" />
      </label>
    </div>
    {#if phase.kind === 'error'}
      <p class="error">{phase.message}</p>
    {/if}
    <button type="submit" class="btn-primary" disabled={phase.kind === 'submitting'}>
      {phase.kind === 'submitting' ? 'Wrapping…' : 'Wrap URL'}
    </button>
  </form>
{/if}

<style>
  .form { display: flex; flex-direction: column; gap: 1rem; }
  .row { display: flex; gap: 1rem; }
  .row label { flex: 1; }
  label { display: flex; flex-direction: column; gap: 4px; }
  label span { font-size: 11px; text-transform: uppercase; letter-spacing: 0.16em; color: #8B847A; font-family: ui-monospace, monospace; }
  input, select { height: 44px; padding: 0 0.75rem; background: transparent; border: 1px solid #C9C2B1; font-family: ui-monospace, monospace; font-size: 14px; color: inherit; border-radius: 0; box-sizing: border-box; }
  input:focus, select:focus { border-color: #E8603C; outline: none; }
  .btn-primary {
    height: 48px;
    background: #E8603C;
    color: white;
    border: none;
    padding: 0 2rem;
    border-radius: 0;
    font-weight: 700;
    cursor: pointer;
    align-self: flex-start;
  }
  .btn-primary:disabled { opacity: 0.5; }
  .success { padding: 1rem 1.25rem; border: 1px solid rgba(46,125,91,0.4); background: rgba(46,125,91,0.05); border-radius: 0; color: #2E7D5B; }
  .head { margin: 0; font-weight: 700; }
  .dim { color: #8B847A; font-size: 12px; }
  .success a { color: inherit; font-family: ui-monospace, monospace; }
  pre { font-family: ui-monospace, monospace; font-size: 12px; padding: 0.5rem; background: rgba(0,0,0,0.05); border-radius: 0; overflow: auto; }
  .error { color: #B43F2A; margin: 0; font-size: 13px; }
  @media (prefers-color-scheme: dark) {
    input, select { border-color: #3A352D; }
    pre { background: rgba(255,255,255,0.05); }
  }
</style>

// apps/web/app/new/wrap-form.tsx
'use client';

import { useState } from 'react';

type Phase =
  | { kind: 'idle' }
  | { kind: 'submitting' }
  | { kind: 'done'; liveUrl: string; redirectUri: string }
  | { kind: 'error'; message: string };

export function WrapForm() {
  const [phase, setPhase] = useState<Phase>({ kind: 'idle' });

  async function onSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const form = new FormData(e.currentTarget);
    setPhase({ kind: 'submitting' });

    const taglineRaw = String(form.get('tagline') ?? '');
    const body = {
      upstream_url: String(form.get('upstream_url') ?? ''),
      slug: String(form.get('slug') ?? ''),
      name: String(form.get('name') ?? ''),
      ...(taglineRaw ? { tagline: taglineRaw } : {}),
      type: String(form.get('type') ?? 'app'),
      category: String(form.get('category') ?? 'tools'),
    };

    const res = await fetch('/api/deploy/wrap', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(body),
    });
    const j = (await res.json().catch(() => ({}))) as {
      success?: boolean;
      live_url?: string;
      runtime_config?: { required_redirect_uris?: string[] };
      reason?: string;
      error?: string;
    };

    if (res.ok && j.success && j.live_url) {
      setPhase({
        kind: 'done',
        liveUrl: j.live_url,
        redirectUri: j.runtime_config?.required_redirect_uris?.[0] ?? '',
      });
    } else {
      setPhase({ kind: 'error', message: j.reason ?? j.error ?? 'Wrap failed.' });
    }
  }

  if (phase.kind === 'done') {
    return (
      <div style={{ padding: 'var(--space-lg)', border: '1px solid var(--border-light)' }}>
        <p
          style={{
            fontFamily: 'var(--font-heading)',
            fontSize: 'var(--h3-size)',
            color: 'var(--sage-leaf, var(--sunset))',
            margin: 0,
          }}
        >
          ✓ Wrapped
        </p>
        <p style={{ marginTop: 'var(--space-sm)' }}>
          <a href={phase.liveUrl} style={{ color: 'var(--sunset)', fontFamily: 'var(--font-mono)' }}>
            {phase.liveUrl}
          </a>
        </p>
        {phase.redirectUri && (
          <>
            <p
              style={{
                marginTop: 'var(--space-md)',
                color: 'var(--text-secondary)',
                fontSize: 'var(--small-size)',
              }}
            >
              Add this redirect URI to your auth provider (Supabase, Auth0, Clerk):
            </p>
            <pre
              style={{
                background: 'var(--surface)',
                border: '1px solid var(--border-light)',
                padding: 'var(--space-sm)',
                fontFamily: 'var(--font-mono)',
                fontSize: 13,
                marginTop: 'var(--space-xs)',
                overflow: 'auto',
              }}
            >
              {phase.redirectUri}
            </pre>
          </>
        )}
      </div>
    );
  }

  return (
    <form
      onSubmit={onSubmit}
      style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-md)' }}
    >
      <Field
        label="Upstream URL"
        name="upstream_url"
        placeholder="https://mevrouw.vercel.app"
        required
        type="url"
      />
      <Field label="Slug" name="slug" placeholder="mevrouw" required pattern="[a-z0-9][a-z0-9-]*[a-z0-9]" />
      <Field label="Name" name="name" placeholder="Mevrouw" required />
      <Field label="Tagline (optional)" name="tagline" />
      <Row>
        <Select
          label="Type"
          name="type"
          options={[
            ['app', 'App'],
            ['web_app', 'Web app'],
            ['website', 'Website'],
          ]}
        />
        <Field label="Category" name="category" placeholder="tools" defaultValue="tools" />
      </Row>
      {phase.kind === 'error' && (
        <p style={{ color: '#c84a2a', fontSize: 'var(--small-size)' }}>{phase.message}</p>
      )}
      <button
        type="submit"
        className="btn-primary"
        disabled={phase.kind === 'submitting'}
        style={{ justifyContent: 'center' }}
      >
        {phase.kind === 'submitting' ? 'Wrapping…' : 'Wrap URL'}
      </button>
    </form>
  );
}

function Field({ label, ...rest }: { label: string } & React.InputHTMLAttributes<HTMLInputElement>) {
  return (
    <label style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
      <span style={{ fontSize: 12, color: 'var(--text-light)' }}>{label}</span>
      <input
        {...rest}
        style={{
          height: 40,
          padding: '0 0.75rem',
          background: 'transparent',
          border: '1px solid var(--border-default)',
          color: 'var(--text-primary)',
          fontFamily: 'var(--font-mono)',
          fontSize: 14,
        }}
      />
    </label>
  );
}

function Select({
  label,
  name,
  options,
}: {
  label: string;
  name: string;
  options: [string, string][];
}) {
  return (
    <label style={{ display: 'flex', flexDirection: 'column', gap: 4, flex: 1 }}>
      <span style={{ fontSize: 12, color: 'var(--text-light)' }}>{label}</span>
      <select
        name={name}
        style={{
          height: 40,
          padding: '0 0.75rem',
          background: 'transparent',
          border: '1px solid var(--border-default)',
          color: 'var(--text-primary)',
        }}
      >
        {options.map(([v, l]) => (
          <option key={v} value={v}>
            {l}
          </option>
        ))}
      </select>
    </label>
  );
}

function Row({ children }: { children: React.ReactNode }) {
  return <div style={{ display: 'flex', gap: 'var(--space-md)' }}>{children}</div>;
}
