// apps/showcase-mevrouw/src/components/ui/button.tsx
import { forwardRef, type ButtonHTMLAttributes } from 'react';
import { cn } from '@/lib/cn.ts';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'destructive';
export type ButtonSize = 'sm' | 'md' | 'lg';

interface Props extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
}

const variantClass: Record<ButtonVariant, string> = {
  primary:
    'bg-[var(--gold)] text-[var(--gold-foreground,oklch(0.13_0.035_150))] hover:brightness-110 active:scale-[0.98]',
  secondary:
    'bg-[var(--secondary)] text-[var(--foreground)] hover:bg-[var(--forest-light)] active:scale-[0.98]',
  ghost:
    'bg-transparent text-[var(--muted-foreground)] hover:text-[var(--foreground)] hover:bg-[var(--forest-light)]',
  destructive:
    'bg-[var(--destructive)] text-white hover:brightness-110 active:scale-[0.98]',
};

const sizeClass: Record<ButtonSize, string> = {
  sm: 'h-8 px-3 text-sm rounded-lg',
  md: 'h-10 px-4 text-sm rounded-xl',
  lg: 'h-12 px-5 text-base rounded-2xl',
};

export const Button = forwardRef<HTMLButtonElement, Props>(function Button(
  { variant = 'primary', size = 'md', className, ...rest },
  ref,
) {
  return (
    <button
      ref={ref}
      className={cn(
        'inline-flex items-center justify-center gap-2 font-medium transition-all',
        'disabled:opacity-50 disabled:cursor-not-allowed',
        'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--background)]',
        variantClass[variant],
        sizeClass[size],
        className,
      )}
      {...rest}
    />
  );
});

// apps/platform/src/lib/components/ui/Button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    variant?: 'primary' | 'secondary' | 'ghost';
    size?: 'sm' | 'md' | 'lg';
    href?: string;
    type?: 'button' | 'submit' | 'reset';
    disabled?: boolean;
    onclick?: (e: MouseEvent) => void;
    children?: Snippet;
    target?: string;
    rel?: string;
    'aria-label'?: string;
  }

  let {
    variant = 'primary',
    size = 'md',
    href,
    type = 'button',
    disabled = false,
    onclick,
    children,
    target,
    rel,
    'aria-label': ariaLabel,
  }: Props = $props();
</script>

{#if href}
  <a
    {href}
    {target}
    {rel}
    aria-label={ariaLabel}
    class="btn variant-{variant} size-{size}"
  >
    {#if children}{@render children()}{/if}
  </a>
{:else}
  <button
    {type}
    {disabled}
    {onclick}
    aria-label={ariaLabel}
    class="btn variant-{variant} size-{size}"
  >
    {#if children}{@render children()}{/if}
  </button>
{/if}

<style>
  .btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    font-family: var(--font-body);
    font-weight: 600;
    border-radius: 0;
    cursor: pointer;
    transition: background var(--duration) var(--ease-out), border-color var(--duration) var(--ease-out);
    text-decoration: none;
    border: 1px solid transparent;
    white-space: nowrap;
  }
  .btn:disabled { opacity: 0.6; cursor: not-allowed; }

  .size-sm { padding: 0.5rem 1.125rem; font-size: var(--small-size); }
  .size-md { padding: 0.75rem 1.5rem; font-size: var(--body-size); }
  .size-lg { padding: 1rem 2.5rem; font-size: clamp(1rem, 2vw, 1.125rem); }

  .variant-primary {
    background: var(--sunset);
    color: var(--bg-pure);
  }
  .variant-primary:hover { background: var(--sunset-hover); }

  .variant-secondary {
    background: transparent;
    color: var(--text);
    border-color: var(--border);
  }
  .variant-secondary:hover { border-color: var(--text-secondary); }

  .variant-ghost {
    background: transparent;
    color: var(--text-secondary);
    border-color: transparent;
  }
  .variant-ghost:hover { color: var(--text); }
</style>
