// apps/web/app/dashboard/apps/[slug]/access/invite-row.tsx
'use client';

import { useState } from 'react';

export interface InviteRowShape {
  id: string;
  token: string;
  kind: string;
  maxUses: number | null;
  usedCount: number;
  expiresAt: Date | string | null;
}

export function InviteRow({ invite, slug }: { invite: InviteRowShape; slug: string }) {
  const [revoked, setRevoked] = useState(false);

  async function revoke() {
    const res = await fetch(`/api/apps/${slug}/invites/${invite.id}`, { method: 'DELETE' });
    if (res.ok) setRevoked(true);
  }

  if (revoked) return null;

  const host = typeof window !== 'undefined' ? window.location.host : 'shippie.app';
  const scheme = typeof window !== 'undefined' ? window.location.protocol : 'https:';
  const url = `${scheme}//${host}/invite/${invite.token}`;
  const uses = invite.maxUses == null ? 'unlimited' : `${invite.maxUses - invite.usedCount} left`;

  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: 'var(--space-md)',
        padding: 'var(--space-sm)',
        border: '1px solid var(--border-light)',
        flexWrap: 'wrap',
      }}
    >
      <code style={{ fontSize: 13, flex: 1, minWidth: 240, overflow: 'hidden', textOverflow: 'ellipsis' }}>
        {url}
      </code>
      <span style={{ fontSize: 12, color: 'var(--text-light)', fontFamily: 'var(--font-mono)' }}>
        {uses}
      </span>
      <button
        onClick={() => void navigator.clipboard.writeText(url)}
        className="btn-secondary"
        style={{ height: 32, padding: '0 0.75rem', fontSize: 13 }}
      >
        Copy
      </button>
      <button
        onClick={revoke}
        className="btn-secondary"
        style={{ height: 32, padding: '0 0.75rem', fontSize: 13 }}
      >
        Revoke
      </button>
    </div>
  );
}

// apps/platform/src/lib/components/dashboard/InviteRow.svelte
<script lang="ts">
  let { slug, invite }: {
    slug: string;
    invite: {
      id: string;
      token: string;
      kind: string;
      maxUses: number | null;
      usedCount: number;
      expiresAt: string | null;
    };
  } = $props();

  let busy = $state(false);
  let revoked = $state(false);
  let error = $state<string | null>(null);
  let confirmingRevoke = $state(false);
  let confirmTimer: number | undefined;

  async function revoke() {
    if (!confirmingRevoke) {
      confirmingRevoke = true;
      error = null;
      if (confirmTimer) window.clearTimeout(confirmTimer);
      confirmTimer = window.setTimeout(() => {
        confirmingRevoke = false;
        confirmTimer = undefined;
      }, 7000);
      return;
    }

    if (confirmTimer) window.clearTimeout(confirmTimer);
    confirmTimer = undefined;
    confirmingRevoke = false;
    busy = true;
    error = null;
    const res = await fetch(`/api/apps/${encodeURIComponent(slug)}/invites/${invite.id}`, {
      method: 'DELETE',
    });
    busy = false;
    if (res.ok) {
      revoked = true;
    } else {
      error = 'Failed to revoke';
    }
  }

  const inviteUrl = $derived(`/invite/${invite.token}`);
</script>

{#if !revoked}
  <div class="row">
    <span class="kind">{invite.kind}</span>
    <a href={inviteUrl} class="url">{inviteUrl}</a>
    <span class="meta">
      {invite.usedCount}{#if invite.maxUses != null}/{invite.maxUses}{/if} used
      {#if invite.expiresAt} · expires {new Date(invite.expiresAt).toLocaleDateString()}{/if}
    </span>
    <button onclick={revoke} disabled={busy}>{busy ? 'Revoking…' : confirmingRevoke ? 'Tap again' : 'Revoke'}</button>
    {#if error}<span class="error">{error}</span>{/if}
    {#if confirmingRevoke}<span class="warning" role="status">Revokes immediately.</span>{/if}
  </div>
{/if}

<style>
  .row {
    display: grid;
    grid-template-columns: auto 1fr auto auto;
    gap: 0.75rem;
    align-items: center;
    padding: 0.625rem 0.75rem;
    border: 1px solid var(--border-light);
    border-radius: 0;
    font-size: 13px;
  }
  .kind { font-family: ui-monospace, monospace; font-size: 11px; padding: 2px 8px; background: rgba(255,255,255,0.06); border-radius: 0; }
  .url { font-family: ui-monospace, monospace; color: var(--sunset); text-decoration: none; }
  .url:hover { text-decoration: underline; }
  .meta { color: var(--text-secondary); font-family: ui-monospace, monospace; font-size: 11px; }
  button { background: transparent; border: 1px solid var(--border-light); color: inherit; padding: 4px 12px; border-radius: 0; cursor: pointer; font-size: 12px; }
  .error { color: var(--danger); font-size: 12px; }
  .warning { color: var(--danger); font-size: 12px; grid-column: 1 / -1; }
</style>
