// apps/web/app/dashboard/apps/[slug]/access/visibility-picker.tsx
'use client';

import { useState } from 'react';

type Scope = 'public' | 'unlisted' | 'private';

const OPTIONS: Array<{ value: Scope; label: string; blurb: string }> = [
  {
    value: 'public',
    label: 'Public',
    blurb: 'Everyone can find it on /apps and /leaderboards.',
  },
  {
    value: 'unlisted',
    label: 'Unlisted',
    blurb: 'Anyone with the URL can see it. Not listed publicly.',
  },
  {
    value: 'private',
    label: 'Private',
    blurb: 'Invitees only. Hidden from /apps, /leaderboards, search.',
  },
];

export function VisibilityPicker({ slug, initial }: { slug: string; initial: Scope }) {
  const [scope, setScope] = useState<Scope>(initial);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  async function onChange(next: Scope) {
    setScope(next);
    setError('');
    setSaving(true);
    const res = await fetch(`/api/apps/${slug}/visibility`, {
      method: 'PATCH',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ visibility_scope: next }),
    });
    setSaving(false);
    if (!res.ok) {
      const j = await res.json().catch(() => ({}));
      setError((j as { error?: string }).error ?? 'Save failed');
      setScope(initial);
    }
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-sm)' }}>
      {OPTIONS.map((opt) => (
        <label
          key={opt.value}
          style={{
            display: 'flex',
            gap: 'var(--space-sm)',
            alignItems: 'flex-start',
            padding: 'var(--space-sm)',
            border: '1px solid var(--border-light)',
            cursor: saving ? 'not-allowed' : 'pointer',
          }}
        >
          <input
            type="radio"
            name="visibility"
            value={opt.value}
            checked={scope === opt.value}
            disabled={saving}
            onChange={() => onChange(opt.value)}
            style={{ marginTop: 4 }}
          />
          <div>
            <strong>{opt.label}</strong>
            <p style={{ fontSize: 13, color: 'var(--text-secondary)', margin: 0 }}>{opt.blurb}</p>
          </div>
        </label>
      ))}
      {error && <p style={{ color: '#c84a2a', fontSize: 13 }}>{error}</p>}
    </div>
  );
}

// apps/platform/src/lib/components/dashboard/VisibilityPicker.svelte
<script lang="ts">
  type Scope = 'public' | 'unlisted' | 'private';

  let { slug, initial }: { slug: string; initial: Scope } = $props();

  let scope = $state<Scope>(initial);
  let saving = $state(false);
  let error = $state<string | null>(null);

  const OPTIONS: Array<{ value: Scope; label: string; blurb: string }> = [
    { value: 'public', label: 'Public', blurb: 'Listed on /apps and /leaderboards.' },
    { value: 'unlisted', label: 'Unlisted', blurb: 'Anyone with the URL can open. Not listed.' },
    { value: 'private', label: 'Private', blurb: 'Invitees only. Hidden from search.' },
  ];

  async function onChange(next: Scope) {
    if (next === scope) return;
    error = null;
    saving = true;
    const res = await fetch(`/api/apps/${encodeURIComponent(slug)}/visibility`, {
      method: 'PATCH',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ visibility_scope: next }),
    });
    saving = false;
    if (!res.ok) {
      const j = (await res.json().catch(() => ({}))) as { error?: string };
      error = j.error ?? 'Save failed';
      return;
    }
    scope = next;
  }
</script>

<div class="picker">
  {#each OPTIONS as opt (opt.value)}
    <label class:active={scope === opt.value}>
      <input
        type="radio"
        name="visibility"
        value={opt.value}
        checked={scope === opt.value}
        disabled={saving}
        onchange={() => onChange(opt.value)}
      />
      <div>
        <strong>{opt.label}</strong>
        <p>{opt.blurb}</p>
      </div>
    </label>
  {/each}
  {#if error}
    <p class="error">{error}</p>
  {/if}
</div>

<style>
  .picker { display: flex; flex-direction: column; gap: 0.5rem; }
  label {
    display: flex;
    gap: 0.75rem;
    align-items: flex-start;
    padding: 0.875rem 1rem;
    border: 1px solid #E5DDC8;
    border-radius: 0;
    cursor: pointer;
  }
  label.active { border-color: #E8603C; background: rgba(232,96,60,0.04); }
  label p { margin: 2px 0 0 0; font-size: 13px; color: #8B847A; }
  .error { color: #B43F2A; font-size: 13px; margin: 0; }
  input[type='radio'] { margin-top: 4px; }
  @media (prefers-color-scheme: dark) {
    label { border-color: #2A251E; }
  }
</style>
