// apps/platform/src/routes/dashboard/apps/+page.svelte
<script lang="ts">
  import type { PageData } from './$types';
  let { data }: { data: PageData } = $props();
</script>

<svelte:head><title>Your apps · Shippie</title></svelte:head>

<header class="header">
  <p class="eyebrow"><a href="/dashboard">Dashboard</a> · apps</p>
  <h1>Your apps</h1>
  <p class="lede">
    {#if data.apps.length === 0}
      You haven't shipped anything yet.
    {:else}
      {data.apps.length} {data.apps.length === 1 ? 'app' : 'apps'}
    {/if}
  </p>
  <a class="ship" href="/new">Ship new app →</a>
</header>

{#if data.apps.length === 0}
  <div class="empty">
    <p class="emoji">🍳</p>
    <h2>Ship your first app</h2>
    <p>Upload a static zip — your app is live at <code>{'{slug}'}.shippie.app</code> in under a minute.</p>
    <a class="btn btn--primary" href="/new">Get started</a>
  </div>
{:else}
  <div class="table-wrap">
    <table>
      <thead>
        <tr>
          <th>App</th>
          <th>Type</th>
          <th>Status</th>
          <th>Visibility</th>
          <th>Last deploy</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {#each data.apps as app (app.id)}
          <tr>
            <td>
              <span class="swatch" style:background={app.themeColor}></span>
              <strong>{app.name}</strong>
              <span class="slug">{app.slug}.shippie.app</span>
            </td>
            <td><span class="badge">{app.type}</span></td>
            <td><span class="status status-{app.latestDeployStatus ?? 'draft'}">{app.latestDeployStatus ?? 'draft'}</span></td>
            <td><span class="vis">{app.visibilityScope}</span></td>
            <td class="time">{formatRelative(app.lastDeployedAt)}</td>
            <td class="right">
              <a href={`/dashboard/apps/${app.slug}`}>Open →</a>
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
{/if}

<script lang="ts" module>
  function formatRelative(iso: string | null): string {
    if (!iso) return 'never';
    const diff = Date.now() - new Date(iso).getTime();
    const m = Math.floor(diff / 60_000);
    if (m < 1) return 'just now';
    if (m < 60) return `${m}m ago`;
    const h = Math.floor(m / 60);
    if (h < 24) return `${h}h ago`;
    const d = Math.floor(h / 24);
    if (d < 30) return `${d}d ago`;
    return `${Math.floor(d / 30)}mo ago`;
  }
</script>

<style>
  .header { display: grid; grid-template-columns: 1fr auto; align-items: end; gap: 1rem; margin-bottom: 2rem; }
  .eyebrow { font-family: ui-monospace, monospace; font-size: 11px; letter-spacing: 0.16em; text-transform: uppercase; color: var(--sunset); margin: 0; }
  .eyebrow a { color: inherit; text-decoration: none; }
  .eyebrow a:hover { text-decoration: underline; }
  h1 { font-family: 'Fraunces', Georgia, serif; font-size: 2.25rem; margin: 0.25rem 0 0.5rem 0; letter-spacing: 0; }
  .lede { color: var(--text-muted-warm); margin: 0; grid-column: 1; }
  .ship { background: var(--sunset); color: white; text-decoration: none; padding: 0 1.5rem; height: 44px; display: inline-flex; align-items: center; border-radius: 0; font-weight: 600; font-size: 14px; }
  .empty { text-align: center; padding: 4rem 2rem; border: 1px dashed var(--border-paper-mid); border-radius: 0; }
  .emoji { font-size: 48px; margin: 0; }
  .empty h2 { font-family: 'Fraunces', Georgia, serif; font-size: 1.75rem; margin: 0.5rem 0; }
  /* "Get started" uses canonical .btn .btn--primary from tokens.css. */
  .table-wrap { border: 1px solid var(--paper-cream); border-radius: 0; overflow: hidden; }
  table { width: 100%; border-collapse: collapse; font-size: 14px; }
  th { text-align: left; padding: 0.75rem 1rem; background: rgba(0,0,0,0.03); font-family: ui-monospace, monospace; font-size: 11px; letter-spacing: 0.16em; text-transform: uppercase; color: var(--text-muted-warm); }
  td { padding: 0.875rem 1rem; border-top: 1px solid rgba(0,0,0,0.06); vertical-align: middle; }
  td.right { text-align: right; }
  td.time { color: var(--text-muted-warm); font-family: ui-monospace, monospace; font-size: 12px; }
  .swatch { display: inline-block; width: 14px; height: 14px; border-radius: 0; margin-right: 0.5rem; vertical-align: middle; }
  .slug { display: block; font-family: ui-monospace, monospace; font-size: 11px; color: var(--text-muted-warm); margin-top: 2px; }
  .badge { font-family: ui-monospace, monospace; font-size: 11px; padding: 2px 8px; border-radius: 0; background: rgba(0,0,0,0.05); }
  .status { font-family: ui-monospace, monospace; font-size: 11px; padding: 2px 8px; border-radius: 0; background: rgba(0,0,0,0.05); }
  .status-success { background: rgba(46,125,91,0.15); color: var(--success); }
  .status-failed { background: rgba(180,63,42,0.15); color: var(--danger); }
  .status-building { background: rgba(232,96,60,0.15); color: var(--danger-hover); }
  .vis { font-family: ui-monospace, monospace; font-size: 11px; color: var(--text-muted-warm); }
  td a { color: var(--sunset); text-decoration: none; font-weight: 600; }
  td a:hover { text-decoration: underline; }
  @media (max-width: 760px) {
    .header {
      grid-template-columns: 1fr;
      align-items: start;
      gap: 0.75rem;
      margin-bottom: 1rem;
    }
    h1 {
      font-size: 2rem;
      line-height: 1.05;
    }
    .ship {
      width: 100%;
      justify-content: center;
    }
    .empty {
      padding: 2rem 1rem;
    }
    .table-wrap {
      border: 0;
      overflow: visible;
    }
    table,
    tbody,
    tr,
    td {
      display: block;
      width: 100%;
      box-sizing: border-box;
    }
    thead {
      display: none;
    }
    tbody {
      display: grid;
      gap: 0.75rem;
    }
    tr {
      padding: 0.85rem;
      border: 1px solid var(--paper-cream);
    }
    td {
      border: 0;
      padding: 0;
    }
    td + td {
      margin-top: 0.5rem;
    }
    td:not(:first-child) {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 1rem;
    }
    td:not(:first-child)::before {
      color: var(--text-muted-warm);
      content: '';
      font-family: ui-monospace, monospace;
      font-size: 10px;
      letter-spacing: 0.12em;
      text-transform: uppercase;
    }
    td:nth-child(2)::before { content: 'Type'; }
    td:nth-child(3)::before { content: 'Status'; }
    td:nth-child(4)::before { content: 'Visibility'; }
    td:nth-child(5)::before { content: 'Last deploy'; }
    td:nth-child(6)::before { content: 'Manage'; }
    td.right {
      text-align: left;
    }
    td.right a {
      min-height: var(--touch-min, 44px);
      display: inline-flex;
      align-items: center;
      color: var(--sunset);
    }
    .slug {
      overflow-wrap: anywhere;
    }
  }
  @media (prefers-color-scheme: dark) {
    .table-wrap { border-color: var(--ink-warm); }
    th { background: rgba(255,255,255,0.04); }
    td { border-color: rgba(255,255,255,0.05); }
    .empty { border-color: var(--ink-warm-mid); }
  }
  @media (prefers-color-scheme: dark) and (max-width: 760px) {
    tr {
      border-color: var(--ink-warm);
    }
  }
</style>

// apps/web/app/dashboard/apps/page.tsx
/**
 * /dashboard/apps — maker's app list.
 *
 * Server component. Queries apps + latest deploy per app, renders a
 * table with slug, name, type, active version, deploy status, last
 * deployed timestamp, and a "Open" link to the live URL.
 *
 * Spec v6 §19 (project structure), Week 4 dashboard target.
 */
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { desc, eq } from 'drizzle-orm';
import { auth } from '@/lib/auth';
import { getDb } from '@/lib/db';
import { schema } from '@shippie/db';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export default async function DashboardAppsPage() {
  const session = await auth();
  if (!session?.user?.id) {
    redirect('/auth/signin?return_to=/dashboard/apps');
  }

  const db = await getDb();
  const rows = await db
    .select({
      id: schema.apps.id,
      slug: schema.apps.slug,
      name: schema.apps.name,
      type: schema.apps.type,
      tagline: schema.apps.tagline,
      themeColor: schema.apps.themeColor,
      latestDeployStatus: schema.apps.latestDeployStatus,
      activeDeployId: schema.apps.activeDeployId,
      lastDeployedAt: schema.apps.lastDeployedAt,
      createdAt: schema.apps.createdAt,
    })
    .from(schema.apps)
    .where(eq(schema.apps.makerId, session.user.id))
    .orderBy(desc(schema.apps.updatedAt));

  return (
    <main className="min-h-screen px-6 py-16">
      <div className="max-w-5xl mx-auto space-y-10">
        <header className="flex items-end justify-between gap-6">
          <div className="space-y-2">
            <p className="text-xs uppercase tracking-widest text-brand-500 font-mono">
              <Link href="/dashboard" className="hover:underline">
                Dashboard
              </Link>{' '}
              · apps
            </p>
            <h1 className="text-4xl font-bold tracking-tight">Your apps</h1>
            <p className="text-neutral-600 dark:text-neutral-400">
              {rows.length === 0
                ? "You haven't shipped anything yet."
                : `${rows.length} app${rows.length === 1 ? '' : 's'} · signed in as ${session.user.email}`}
            </p>
          </div>
          <Link
            href="/new"
            className="inline-flex h-11 items-center rounded-full bg-brand-500 px-6 text-white font-medium hover:bg-brand-600 transition-colors whitespace-nowrap"
          >
            Ship new app →
          </Link>
        </header>

        {rows.length === 0 ? (
          <EmptyState />
        ) : (
          <div className="rounded-xl border border-neutral-300 dark:border-neutral-700 overflow-hidden">
            <table className="w-full text-sm">
              <thead className="bg-neutral-100 dark:bg-neutral-900">
                <tr>
                  <Th>App</Th>
                  <Th>Type</Th>
                  <Th>Status</Th>
                  <Th>Last deploy</Th>
                  <Th className="text-right">Actions</Th>
                </tr>
              </thead>
              <tbody>
                {rows.map((app) => (
                  <tr
                    key={app.id}
                    className="border-t border-neutral-200 dark:border-neutral-800"
                  >
                    <Td>
                      <div className="flex items-center gap-3">
                        <span
                          className="inline-block w-8 h-8 rounded-lg"
                          style={{ background: app.themeColor }}
                          aria-hidden
                        />
                        <div>
                          <div className="font-semibold">{app.name}</div>
                          <div className="text-xs font-mono text-neutral-500">
                            {app.slug}.shippie.app
                          </div>
                        </div>
                      </div>
                    </Td>
                    <Td>
                      <TypeBadge type={app.type} />
                    </Td>
                    <Td>
                      <StatusBadge status={app.latestDeployStatus} />
                    </Td>
                    <Td className="text-neutral-500 font-mono text-xs">
                      {app.lastDeployedAt
                        ? formatRelative(new Date(app.lastDeployedAt))
                        : 'never'}
                    </Td>
                    <Td className="text-right">
                      <a
                        href={devUrl(app.slug)}
                        target="_blank"
                        rel="noreferrer"
                        className="text-brand-500 hover:underline font-medium"
                      >
                        Open →
                      </a>
                    </Td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </main>
  );
}

function EmptyState() {
  return (
    <div className="rounded-xl border border-dashed border-neutral-300 dark:border-neutral-700 p-16 text-center space-y-6">
      <p className="text-6xl" aria-hidden>
        🍳
      </p>
      <h2 className="text-2xl font-bold">Ship your first app</h2>
      <p className="max-w-md mx-auto text-neutral-600 dark:text-neutral-400">
        Upload a static zip or connect a GitHub repo and your app is live at{' '}
        <code className="font-mono text-sm">{'<slug>'}.shippie.app</code> in under a
        minute.
      </p>
      <Link
        href="/new"
        className="inline-flex h-12 items-center rounded-full bg-brand-500 px-8 text-white font-medium hover:bg-brand-600 transition-colors"
      >
        Get started
      </Link>
    </div>
  );
}

function TypeBadge({ type }: { type: string }) {
  const label = type === 'app' ? 'App' : type === 'web_app' ? 'Web App' : 'Site';
  return (
    <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-mono bg-neutral-100 dark:bg-neutral-900 text-neutral-700 dark:text-neutral-300">
      {label}
    </span>
  );
}

function StatusBadge({ status }: { status: string | null }) {
  const palette: Record<string, string> = {
    success:
      'bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-200',
    building:
      'bg-amber-100 dark:bg-amber-950 text-amber-700 dark:text-amber-200',
    needs_secrets:
      'bg-violet-100 dark:bg-violet-950 text-violet-700 dark:text-violet-200',
    failed: 'bg-red-100 dark:bg-red-950 text-red-700 dark:text-red-200',
  };
  const key = status ?? 'none';
  const className = palette[key] ?? 'bg-neutral-100 dark:bg-neutral-900 text-neutral-500';
  return (
    <span
      className={`inline-flex items-center px-2 py-0.5 rounded-full text-xs font-mono ${className}`}
    >
      {status ?? 'draft'}
    </span>
  );
}

function Th({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return (
    <th
      className={`text-left text-xs font-mono uppercase tracking-widest text-neutral-500 font-semibold px-4 py-3 ${className}`}
    >
      {children}
    </th>
  );
}

function Td({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return <td className={`px-4 py-3 align-middle ${className}`}>{children}</td>;
}

function devUrl(slug: string): string {
  // Dev: open against the local worker on port 4200. Prod points at
  // https://{slug}.shippie.app directly.
  if (process.env.NODE_ENV === 'production') {
    return `https://${slug}.shippie.app/`;
  }
  const port = process.env.SHIPPIE_WORKER_PORT ?? '4200';
  return `http://${slug}.localhost:${port}/`;
}

function formatRelative(date: Date): string {
  const diffMs = Date.now() - date.getTime();
  const minutes = Math.floor(diffMs / 60_000);
  if (minutes < 1) return 'just now';
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 30) return `${days}d ago`;
  const months = Math.floor(days / 30);
  return `${months}mo ago`;
}
