// apps/web/app/dashboard/apps/[slug]/access/page.tsx
import { notFound } from 'next/navigation';
import { eq } from 'drizzle-orm';
import { schema } from '@shippie/db';
import { auth } from '@/lib/auth';
import { getDb } from '@/lib/db';
import { SiteNav } from '@/app/components/site-nav';
import { CreateInviteForm } from './create-invite-form';
import { InviteRow } from './invite-row';
import { VisibilityPicker } from './visibility-picker';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export default async function AccessPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const session = await auth();
  if (!session?.user?.id) notFound();

  const db = await getDb();
  const [app] = await db.select().from(schema.apps).where(eq(schema.apps.slug, slug)).limit(1);
  if (!app || app.makerId !== session.user.id) notFound();

  const invites = await db
    .select()
    .from(schema.appInvites)
    .where(eq(schema.appInvites.appId, app.id))
    .orderBy(schema.appInvites.createdAt);

  const access = await db
    .select()
    .from(schema.appAccess)
    .where(eq(schema.appAccess.appId, app.id));

  const activeInvites = invites.filter((i) => i.revokedAt == null);

  return (
    <>
      <SiteNav />
      <main
        style={{
          maxWidth: 900,
          margin: '0 auto',
          padding: 'var(--space-xl)',
          paddingTop: 'calc(var(--nav-height) + var(--safe-top) + var(--space-xl))',
        }}
      >
        <header style={{ marginBottom: 'var(--space-xl)' }}>
          <p className="eyebrow">Access · {app.name}</p>
          <h1
            style={{
              fontFamily: 'var(--font-heading)',
              fontSize: '2rem',
              letterSpacing: '-0.02em',
              margin: '0.25rem 0 var(--space-sm)',
            }}
          >
            Who can see this app
          </h1>
        </header>

        <section style={{ marginBottom: 'var(--space-2xl)' }}>
          <h2
            style={{
              fontFamily: 'var(--font-heading)',
              fontSize: '1.25rem',
              marginBottom: 'var(--space-md)',
            }}
          >
            Visibility
          </h2>
          <VisibilityPicker
            slug={slug}
            initial={app.visibilityScope as 'public' | 'unlisted' | 'private'}
          />
        </section>

        <section style={{ marginBottom: 'var(--space-2xl)' }}>
          <h2
            style={{
              fontFamily: 'var(--font-heading)',
              fontSize: '1.25rem',
              marginBottom: 'var(--space-md)',
            }}
          >
            Create invite link
          </h2>
          <CreateInviteForm slug={slug} />
        </section>

        <section style={{ marginBottom: 'var(--space-2xl)' }}>
          <h2
            style={{
              fontFamily: 'var(--font-heading)',
              fontSize: '1.25rem',
              marginBottom: 'var(--space-md)',
            }}
          >
            Active invites
          </h2>
          {activeInvites.length === 0 ? (
            <p style={{ color: 'var(--text-light)' }}>No invites yet.</p>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-sm)' }}>
              {activeInvites.map((inv) => (
                <InviteRow
                  key={inv.id}
                  slug={slug}
                  invite={{
                    id: inv.id,
                    token: inv.token,
                    kind: inv.kind,
                    maxUses: inv.maxUses,
                    usedCount: inv.usedCount,
                    expiresAt: inv.expiresAt,
                  }}
                />
              ))}
            </div>
          )}
        </section>

        <section>
          <h2
            style={{
              fontFamily: 'var(--font-heading)',
              fontSize: '1.25rem',
              marginBottom: 'var(--space-md)',
            }}
          >
            Access list
          </h2>
          {access.length === 0 ? (
            <p style={{ color: 'var(--text-light)' }}>Nobody has claimed yet.</p>
          ) : (
            <ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>
              {access.map((a) => (
                <li
                  key={a.id}
                  style={{
                    padding: 'var(--space-sm) 0',
                    borderBottom: '1px solid var(--border-light)',
                    fontFamily: 'var(--font-mono)',
                    fontSize: 13,
                    color: 'var(--text-secondary)',
                  }}
                >
                  {a.userId ?? a.email ?? '—'} · {a.source} · {a.grantedAt.toISOString()}
                </li>
              ))}
            </ul>
          )}
        </section>
      </main>
    </>
  );
}

// apps/platform/src/routes/dashboard/apps/[slug]/access/+page.svelte
<script lang="ts">
  import VisibilityPicker from '$components/dashboard/VisibilityPicker.svelte';
  import CreateInviteForm from '$components/dashboard/CreateInviteForm.svelte';
  import InviteRow from '$components/dashboard/InviteRow.svelte';
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();
  const activeInvites = $derived(data.invites.filter((i) => i.revokedAt == null));
</script>

<svelte:head><title>Access · {data.app.name}</title></svelte:head>

<section class="block">
  <h2>Visibility</h2>
  <VisibilityPicker slug={data.app.slug} initial={data.app.visibilityScope as 'public' | 'unlisted' | 'private'} />
</section>

<section class="block">
  <h2>Create invite link</h2>
  <CreateInviteForm slug={data.app.slug} />
</section>

<section class="block">
  <h2>Active invites</h2>
  {#if activeInvites.length === 0}
    <p class="muted">No invites yet.</p>
  {:else}
    <div class="invite-list">
      {#each activeInvites as inv (inv.id)}
        <InviteRow slug={data.app.slug} invite={{
          id: inv.id,
          token: inv.token,
          kind: inv.kind,
          maxUses: inv.maxUses,
          usedCount: inv.usedCount,
          expiresAt: inv.expiresAt,
        }} />
      {/each}
    </div>
  {/if}
</section>

<section class="block">
  <h2>Access list</h2>
  {#if data.access.length === 0}
    <p class="muted">Nobody has claimed yet.</p>
  {:else}
    <ul>
      {#each data.access as a (a.id)}
        <li>{a.userId ?? a.email ?? '—'} · {a.source} · {a.grantedAt}</li>
      {/each}
    </ul>
  {/if}
</section>

<style>
  .block { margin-bottom: 2.5rem; }
  h2 { font-family: 'Fraunces', Georgia, serif; font-size: 1.25rem; margin: 0 0 0.75rem 0; }
  .muted { color: #8B847A; }
  .invite-list { display: flex; flex-direction: column; gap: 0.5rem; }
  ul { list-style: none; padding: 0; margin: 0; }
  ul li { padding: 0.5rem 0; border-bottom: 1px solid rgba(0,0,0,0.06); font-family: ui-monospace, monospace; font-size: 13px; color: #8B847A; }
  @media (prefers-color-scheme: dark) {
    ul li { border-color: rgba(255,255,255,0.05); }
  }
</style>
