// apps/platform/src/routes/apps/[slug]/+page.svelte
<script lang="ts">
  import type { PageProps } from './$types';
  import IconOrMonogram from '$lib/components/marketplace/IconOrMonogram.svelte';
  import RatingsSummary from '$lib/components/marketplace/RatingsSummary.svelte';
  import CapabilityBadges from '$lib/components/marketplace/CapabilityBadges.svelte';
  import UpvoteButton from '$lib/components/marketplace/UpvoteButton.svelte';
  import Button from '$lib/components/ui/Button.svelte';

  let { data }: PageProps = $props();

  // Subdomain for direct install. `shippie.app` post-cutover; the canary
  // form was `next.shippie.app` which still works since the wildcard
  // route covers both hostnames.
  function installUrl(slug: string): string {
    return `https://${slug}.shippie.app/`;
  }
</script>

<svelte:head>
  <title>{data.app.name} — Shippie</title>
  <meta name="description" content={data.app.tagline ?? data.app.description ?? `${data.app.name} on Shippie`} />
</svelte:head>

<header class="hero" style="background: {data.app.themeColor};">
  <div class="hero-wrap">
    <a href="/apps" class="back">← All apps</a>
    <div class="hero-row">
      <IconOrMonogram
        name={data.app.name}
        slug={data.app.slug}
        iconUrl={data.app.iconUrl}
        themeColor={data.app.themeColor}
        size={96}
      />
      <div class="hero-meta">
        <h1 class="title">{data.app.name}</h1>
        <p class="tagline">{data.app.tagline ?? data.app.description ?? ''}</p>
        <p class="kind">{data.app.type} · {data.app.category}</p>
        {#if data.capabilityBadges.length > 0}
          <div class="badges">
            <CapabilityBadges badges={data.capabilityBadges} max={5} />
          </div>
        {/if}
        <div class="cta-row">
          <a class="install-btn" href={data.ownership.standaloneUrl}>
            Open {data.app.name}
          </a>
          <UpvoteButton slug={data.app.slug} initialCount={data.app.upvoteCount} />
        </div>
      </div>
    </div>
  </div>
</header>

<div class="body wrap">
  {#if data.grantedPermissions.length > 0}
    <section class="section">
      <h2>What this app can do</h2>
      <ul class="perms">
        {#each data.grantedPermissions as perm (perm)}
          <li>
            <span class="check" aria-hidden="true">✓</span>
            <span>{perm}</span>
          </li>
        {/each}
      </ul>
    </section>
  {/if}

  {#if data.changelog && data.changelog.entries.length > 0}
    <section class="section">
      <h2>Latest changes</h2>
      <p class="changelog-summary">{data.changelog.summary}</p>
      <ul class="changelog-entries">
        {#each data.changelog.entries as entry, i (i)}
          <li>{entry}</li>
        {/each}
      </ul>
    </section>
  {/if}

  <section class="section ownership">
    <div>
      <h2>Maker &amp; Ownership</h2>
      <p>
        Made by {data.ownership.maker.name}
        {#if data.ownership.maker.username}
          <span class="muted">(@{data.ownership.maker.username})</span>
        {/if}
        {#if data.ownership.maker.verified}
          <span class="pill">Verified maker</span>
        {/if}
      </p>
    </div>
    <div class="ownership-grid">
      <article>
        <span>Standalone URL</span>
        <a href={data.ownership.standaloneUrl} target="_blank" rel="noopener">
          {new URL(data.ownership.standaloneUrl).host}
        </a>
      </article>
      <article>
        <span>Custom domains</span>
        {#if data.ownership.customDomains.length > 0}
          <div class="domain-list">
            {#each data.ownership.customDomains as domain (domain.domain)}
              <a href={`https://${domain.domain}/`} target="_blank" rel="noopener">
                {domain.domain}{domain.isCanonical ? ' · canonical' : ''}
              </a>
            {/each}
          </div>
        {:else}
          <p class="muted">None verified yet</p>
        {/if}
      </article>
      <article>
        <span>Source</span>
        {#if data.ownership.sourceRepo}
          <a href={data.ownership.sourceRepo} target="_blank" rel="noopener">View source</a>
        {:else}
          <p class="muted">Source not published</p>
        {/if}
      </article>
      <article>
        <span>License &amp; remix</span>
        <p>
          {data.ownership.license ?? 'Unlicensed'}
          · {data.ownership.remixAllowed ? 'Remix allowed' : 'Remix closed'}
        </p>
      </article>
    </div>
    {#if data.ownership.versions.length > 0}
      <div class="version-strip" aria-label="Recent versions">
        {#each data.ownership.versions as version (version.packageHash)}
          <a href={version.packageUrl}>
            v{version.version}
            · {version.channel}
            · {version.containerEligibility.replace('_', ' ')}
          </a>
        {/each}
      </div>
    {/if}
    <div class="ownership-actions">
      {#if data.ownership.sourceRepo}
        <a href={data.ownership.sourceRepo} target="_blank" rel="noopener">View source</a>
      {/if}
      {#if data.ownership.remixAllowed}
        <a href={`/new?remix=${data.app.slug}`}>Remix this app</a>
      {:else}
        <span>Remix unavailable until the maker publishes source + license</span>
      {/if}
    </div>
  </section>

  {#if data.ratingSummary.count > 0}
    <section class="section">
      <h2>Ratings &amp; reviews</h2>
      <RatingsSummary summary={data.ratingSummary} latest={data.latestReviews} />
    </section>
  {/if}

  <section class="section meta-row">
    <p class="meta-line">
      {data.app.installCount.toLocaleString()} installs · {data.app.upvoteCount.toLocaleString()} upvotes
    </p>
  </section>

  {#if data.isMaker}
    <section class="section">
      <Button href={`/dashboard/apps/${data.app.slug}`} variant="secondary">
        Open in dashboard →
      </Button>
    </section>
  {/if}
</div>

<style>
  .hero {
    color: #EDE4D3;
    padding: var(--space-2xl) 0;
  }
  .hero-wrap {
    max-width: 880px;
    margin: 0 auto;
    padding: 0 clamp(1.5rem, 4vw, 3rem);
  }
  .back {
    display: inline-block;
    font-family: var(--font-mono);
    font-size: var(--caption-size);
    letter-spacing: 0.2em;
    text-transform: uppercase;
    color: #EDE4D3;
    opacity: 0.85;
    margin-bottom: var(--space-xl);
  }
  .back:hover { opacity: 1; }
  .hero-row {
    display: flex;
    gap: var(--space-lg);
    align-items: flex-start;
    flex-wrap: wrap;
  }
  .hero-meta { flex: 1; min-width: 240px; }
  .title {
    font-family: var(--font-heading);
    font-size: clamp(2rem, 5vw, 3rem);
    line-height: 1.1;
    letter-spacing: -0.02em;
    margin: 0;
    color: #EDE4D3;
  }
  .tagline {
    margin-top: 0.5rem;
    font-size: 1.125rem;
    opacity: 0.92;
    color: #EDE4D3;
  }
  .kind {
    font-family: var(--font-mono);
    font-size: var(--caption-size);
    letter-spacing: 0.1em;
    text-transform: uppercase;
    opacity: 0.75;
    margin-top: 0.625rem;
  }
  .badges { margin-top: 1rem; }
  .cta-row {
    margin-top: var(--space-lg);
    display: flex;
    gap: 0.75rem;
    flex-wrap: wrap;
  }
  .install-btn {
    display: inline-flex;
    align-items: center;
    height: 44px;
    padding: 0 1.25rem;
    background: #14120F;
    color: var(--marigold);
    font-weight: 600;
    font-size: var(--small-size);
    transition: background 0.2s;
  }
  .install-btn:hover { background: #000; }

  .body {
    padding: var(--space-2xl) 0 var(--space-3xl);
    max-width: 880px;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    gap: var(--space-2xl);
  }
  .section h2 {
    font-family: var(--font-heading);
    font-size: 1.25rem;
    margin: 0 0 var(--space-md);
    letter-spacing: -0.01em;
  }
  .perms {
    list-style: none;
    margin: 0;
    padding: 0;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 8px 24px;
    font-size: var(--small-size);
  }
  @media (max-width: 480px) {
    .perms { grid-template-columns: 1fr; }
  }
  .perms li {
    display: flex;
    gap: 8px;
    align-items: center;
    color: var(--text-secondary);
  }
  .check { color: var(--sage-leaf); }
  .changelog-summary { margin: 0 0 var(--space-sm); font-weight: 500; }
  .changelog-entries {
    list-style: none;
    padding: 0;
    margin: 0;
    color: var(--text-secondary);
    font-size: var(--small-size);
    line-height: 1.7;
  }
  .changelog-entries li::before { content: '· '; }
  .meta-row { color: var(--text-light); font-family: var(--font-mono); font-size: var(--small-size); }
  .meta-line { margin: 0; }
  .ownership {
    display: grid;
    gap: var(--space-md);
  }
  .ownership p {
    margin: 0;
    color: var(--text-secondary);
  }
  .muted {
    color: var(--text-light);
  }
  .pill {
    display: inline-flex;
    margin-left: 0.5rem;
    padding: 2px 8px;
    border: 1px solid var(--sage-leaf);
    border-radius: 0;
    color: var(--sage-leaf);
    font-family: var(--font-mono);
    font-size: var(--caption-size);
  }
  .ownership-grid {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: var(--space-md);
  }
  .ownership-grid article {
    min-width: 0;
    padding: var(--space-md);
    border: 1px solid var(--border-light);
    border-radius: 0;
    background: var(--surface);
    display: grid;
    gap: 6px;
  }
  .ownership-grid span,
  .version-strip {
    font-family: var(--font-mono);
    font-size: var(--caption-size);
    color: var(--text-light);
  }
  .ownership-grid a {
    color: var(--sunset);
    overflow-wrap: anywhere;
  }
  .domain-list {
    display: grid;
    gap: 4px;
  }
  .version-strip {
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
  }
  .version-strip a {
    border: 1px solid var(--border-light);
    border-radius: 0;
    padding: 4px 8px;
    color: var(--text-secondary);
  }
  .ownership-actions {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
  }
  .ownership-actions a,
  .ownership-actions span {
    padding: 0.55rem 0.75rem;
    border: 1px solid var(--border-light);
    border-radius: 0;
    background: var(--bg-pure);
    color: var(--text-secondary);
    font-size: var(--small-size);
  }
  .ownership-actions a {
    color: var(--sunset);
  }
  @media (max-width: 640px) {
    .ownership-grid {
      grid-template-columns: 1fr;
    }
  }
</style>

// apps/web/app/apps/[slug]/page.tsx
/**
 * /apps/[slug] — App detail / listing page.
 *
 * Flat hero (no gradients). Square icon. Sunset only on primary CTA.
 */
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { eq, desc } from 'drizzle-orm';
import { schema } from '@shippie/db';
import { getDb } from '@/lib/db';
import { auth } from '@/lib/auth';
import {
  queryRatingSummary,
  queryLatestReviews,
  queryUserRating,
} from '@/lib/shippie/ratings';
import { RatingsSummary } from '@/app/components/ratings-summary';
import { InstallButton } from './install-button';
import { RateWidget } from './rate-widget';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

function devInstallUrl(slug: string): string {
  return `http://${slug}.localhost:4200/`;
}

export default async function AppDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const db = await getDb();

  const app = await db.query.apps.findFirst({ where: eq(schema.apps.slug, slug) });
  if (!app) notFound();

  const [latestDeploy] = await db.select().from(schema.deploys)
    .where(eq(schema.deploys.appId, app.id)).orderBy(desc(schema.deploys.version)).limit(1);

  const permissions = await db.query.appPermissions.findFirst({
    where: eq(schema.appPermissions.appId, app.id),
  });

  const autopack = (latestDeploy?.autopackagingReport ?? null) as {
    compat?: { score: number; findings: Array<{ severity: string; message: string }> };
    changelog?: { source: string; entries: string[]; summary: string };
  } | null;

  const externalDomains = latestDeploy
    ? await db.query.appExternalDomains.findMany({ where: eq(schema.appExternalDomains.deployId, latestDeploy.id) })
    : [];

  const compatScore = autopack?.compat?.score ?? app.compatibilityScore ?? 0;

  const [ratingSummary, latestReviews, session] = await Promise.all([
    queryRatingSummary(db, slug),
    queryLatestReviews(db, slug, 5),
    auth(),
  ]);
  const userId = (session?.user as { id?: string } | undefined)?.id ?? null;
  const userRating = userId ? await queryUserRating(db, slug, userId) : null;

  return (
    <main className="min-h-screen" style={{ background: 'var(--bg-primary)', color: 'var(--text-primary)' }}>
      <header className="px-6 py-20" style={{ background: app.themeColor, color: '#EDE4D3' }}>
        <div className="max-w-4xl mx-auto">
          <Link href="/apps" className="text-xs font-mono opacity-80 hover:opacity-100 uppercase" style={{ letterSpacing: '0.2em' }}>
            ← All apps
          </Link>
          <div className="mt-6 flex items-start gap-6">
            <div className="w-24 h-24 shippie-icon flex-shrink-0" style={{ background: 'rgba(255,255,255,0.1)' }} aria-hidden />
            <div>
              <h1 className="text-display text-4xl md:text-5xl">{app.name}</h1>
              <p className="mt-2 text-lg opacity-90">{app.tagline ?? app.description ?? ''}</p>
              <p className="mt-3 text-xs font-mono opacity-75 uppercase" style={{ letterSpacing: '0.1em' }}>
                {app.type} · {app.category} · v{latestDeploy?.version ?? '?'}
              </p>
              <div className="mt-6 flex flex-wrap gap-3">
                <a href={devInstallUrl(app.slug)} target="_blank" rel="noopener"
                  className="inline-block h-12 px-6 font-medium leading-[48px] transition-colors"
                  style={{ background: 'var(--action-primary)', color: '#14120F' }}>
                  Open app
                </a>
                <InstallButton url={devInstallUrl(app.slug)} name={app.name} />
              </div>
            </div>
          </div>
        </div>
      </header>

      <div className="max-w-4xl mx-auto px-6 py-12 space-y-12">
        <section className="space-y-3">
          <h2 className="text-2xl font-semibold">Compatibility</h2>
          <div className="flex items-center gap-3">
            <span className="text-3xl" style={{ color: 'var(--green-leaf)' }}>{'★'.repeat(compatScore)}{'☆'.repeat(5 - compatScore)}</span>
            <span style={{ color: 'var(--text-muted)' }}>{compatScore}/5</span>
          </div>
          {autopack?.compat?.findings && autopack.compat.findings.length > 0 && (
            <ul className="mt-4 space-y-2 text-sm">
              {autopack.compat.findings.map((f, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span style={{ color: f.severity === 'match' ? 'var(--semantic-success)' : f.severity === 'violation' ? 'var(--semantic-error)' : 'var(--semantic-warning)' }}>
                    {f.severity === 'match' ? '✓' : f.severity === 'violation' ? '✗' : '⚠'}
                  </span>
                  <span style={{ color: 'var(--text-secondary)' }}>{f.message}</span>
                </li>
              ))}
            </ul>
          )}
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-semibold">Permissions</h2>
          <ul className="grid grid-cols-2 gap-2 text-sm">
            <PermRow label="Sign in" on={permissions?.auth ?? false} />
            <PermRow label="User storage" on={(permissions?.storage ?? 'none') !== 'none'} />
            <PermRow label="File uploads" on={permissions?.files ?? false} />
            <PermRow label="Notifications" on={permissions?.notifications ?? false} />
            <PermRow label="Analytics" on={permissions?.analytics ?? true} />
            <PermRow label="External network" on={permissions?.externalNetwork ?? false} />
          </ul>
        </section>

        {externalDomains.length > 0 && (
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">External domains</h2>
            <ul className="text-sm font-mono space-y-1">
              {externalDomains.map((d: { domain: string; source: string; allowed: boolean }) => (
                <li key={d.domain} className="flex items-center gap-2">
                  <span style={{ color: d.allowed ? 'var(--semantic-success)' : 'var(--semantic-warning)' }}>{d.allowed ? '✓' : '⚠'}</span>
                  <span>{d.domain}</span>
                  <span style={{ color: 'var(--text-muted)' }}>({d.source})</span>
                </li>
              ))}
            </ul>
          </section>
        )}

        {autopack?.changelog && (
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">Latest changes</h2>
            <p className="font-medium">{autopack.changelog.summary}</p>
            {autopack.changelog.entries.length > 0 && (
              <ul className="text-sm space-y-1 ml-4" style={{ color: 'var(--text-secondary)' }}>
                {autopack.changelog.entries.map((e, i) => <li key={i}>· {e}</li>)}
              </ul>
            )}
            <p className="text-xs font-mono" style={{ color: 'var(--text-muted)' }}>source: {autopack.changelog.source}</p>
          </section>
        )}

        <section style={{ marginTop: 'var(--space-2xl, 4rem)' }}>
          <h2 style={{ fontFamily: 'var(--font-heading)', fontSize: '1.25rem', marginBottom: 16 }}>
            Ratings &amp; reviews
          </h2>
          <RatingsSummary summary={ratingSummary} latest={latestReviews} />
          {userId && <RateWidget slug={slug} initial={userRating} />}
        </section>
      </div>
    </main>
  );
}

function PermRow({ label, on }: { label: string; on: boolean }) {
  return (
    <li className="flex items-center gap-2">
      <span style={{ color: on ? 'var(--semantic-success)' : 'var(--text-muted)' }}>{on ? '✓' : '—'}</span>
      <span style={{ color: on ? 'var(--text-primary)' : 'var(--text-muted)' }}>{label}</span>
    </li>
  );
}
